//! Sorted, three-byte model-variant records generated by the GoldSrc cooker.

/// Resolve a map/type pair to its little-endian chunk identifier.
/// Offsets count records, each encoded as `[type, chunk_lo, chunk_hi]`.
/// Rows must be sorted by type. Map/type indices come from the cooked map
/// domain; `map_index` must be less than `usize::MAX`.
#[inline]
pub fn lookup(
    offsets: &[u16],
    bytes: &[u8],
    map_index: usize,
    ty: usize,
    type_count: usize,
) -> Option<u32> {
    if map_index + 1 >= offsets.len() || ty >= type_count {
        return None;
    }
    let mut entry = offsets[map_index] as usize;
    let end = offsets[map_index + 1] as usize;
    while entry < end {
        let offset = entry * 3;
        if offset + 2 >= bytes.len() {
            return None;
        }
        let entry_ty = bytes[offset] as usize;
        if entry_ty == ty {
            return Some(u16::from_le_bytes([bytes[offset + 1], bytes[offset + 2]]) as u32);
        }
        if entry_ty > ty {
            return None;
        }
        entry += 1;
    }
    None
}
