//! Public embedded-play viewport API shared with the frontend.

use egui::{Color32, Pos2, Rect, Vec2};

/// Request emitted by the editor UI for embedded play mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EditorPlaytestRequest {
    /// Build/load and start play mode. The frontend performs the
    /// cook step before compiling the runtime.
    Play,
    /// Stop play mode and return to edit preview.
    Stop,
    /// Re-cook/rebuild/reload while play mode is already active.
    Rebuild,
    /// Build the current project and export the resulting EXE to the
    /// launcher Projects list. The frontend performs the cook step
    /// first, then compiles the runtime.
    BuildProject,
    /// The playable viewport was clicked; capture game input there.
    CaptureInput,
}

/// Frontend-owned embedded playtest state, mirrored into the editor
/// for toolbar labels and the playable viewport overlay.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EditorPlaytestStatus {
    /// No active or recent play mode.
    #[default]
    Idle,
    /// The active project is being cooked.
    Cooking,
    /// `make build-editor-playtest` is running in the frontend.
    Building,
    /// The editor viewport is showing the live in-process emulator.
    Running { input_captured: bool },
    /// The last embedded play attempt failed.
    Failed,
}

impl EditorPlaytestStatus {
    /// True while a Play / Stop pair should be offered.
    pub const fn is_active(self) -> bool {
        matches!(self, Self::Cooking | Self::Building | Self::Running { .. })
    }

    /// True when the 3D viewport should render the live game output.
    pub const fn is_playing(self) -> bool {
        matches!(self, Self::Running { .. })
    }
}

/// What the 3D editor viewport should paint this frame.
#[derive(Clone)]
pub struct EditorViewport3dPresentation {
    /// Egui texture to paint into the 3D viewport.
    pub texture: egui::TextureId,
    /// UV region inside `texture`.
    pub uv: Rect,
    /// Whether this is the editable preview or embedded play output.
    pub mode: EditorViewport3dMode,
    /// Editor-only screen-space overlays, in `overlay_source_size`
    /// coordinates. Kept out of the PSX-style preview command log so
    /// editor affordances can use host UI strokes, alpha, and
    /// fractional widths.
    pub overlay_lines: Vec<EditorViewportOverlayLine>,
    /// Logical source rectangle for `overlay_lines`.
    pub overlay_source_size: Vec2,
    /// Frontend-profiler metrics for live embedded play. These are
    /// emulator measurements, not egui repaint cadence.
    pub play_metrics: Option<EditorPlaytestMetrics>,
}

impl EditorViewport3dPresentation {
    /// Editable 3D preview generated by the editor preview renderer.
    pub fn edit(texture: egui::TextureId, overlay_lines: Vec<EditorViewportOverlayLine>) -> Self {
        Self {
            texture,
            uv: Rect::from_min_max(
                egui::pos2(0.0, 0.0),
                egui::pos2(640.0 / 2048.0, 480.0 / 1024.0),
            ),
            mode: EditorViewport3dMode::Edit,
            overlay_lines,
            overlay_source_size: egui::vec2(320.0, 240.0),
            play_metrics: None,
        }
    }

    /// Live game output generated by the frontend emulator.
    pub fn play(
        texture: egui::TextureId,
        uv: Rect,
        play_metrics: Option<EditorPlaytestMetrics>,
    ) -> Self {
        Self {
            texture,
            uv,
            mode: EditorViewport3dMode::Play,
            overlay_lines: Vec::new(),
            overlay_source_size: Vec2::ZERO,
            play_metrics,
        }
    }
}

/// Rolling emulator metrics shown over the live editor Play viewport.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorPlaytestMetrics {
    /// Host redraw rate from the frontend profiler.
    pub host_fps: f32,
    /// Average host frame time.
    pub host_ms: f32,
    /// Emulated VBlank rate per host second.
    pub emu_hz: f32,
    /// VBlanks that produced draw traffic per guest refresh.
    pub draw_hz: f32,
    /// Full frontend frame cost.
    pub total_ms: f32,
    /// Guest execution cost.
    pub emu_ms: f32,
    /// Hardware renderer cost.
    pub hw_ms: f32,
    /// egui/wgpu UI cost.
    pub ui_ms: f32,
    /// Guest cycle budget consumed by stepped frames.
    pub step_budget_percent: f32,
}

/// One host-drawn editor overlay segment over the 3D preview.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorViewportOverlayLine {
    pub a: Pos2,
    pub b: Pos2,
    pub color: Color32,
    pub width: f32,
}

impl EditorViewportOverlayLine {
    pub const fn new(a: Pos2, b: Pos2, color: Color32, width: f32) -> Self {
        Self { a, b, color, width }
    }
}

/// Mode for the 3D viewport presentation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EditorViewport3dMode {
    /// Editable authoring preview.
    Edit,
    /// Embedded emulator framebuffer.
    Play,
}
