//! Public embedded-play viewport API shared with the frontend.

use egui::{Color32, Pos2, Rect, Vec2};

/// Request emitted by the editor UI for embedded play mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EditorPlaytestRequest {
    /// Build/load and start play mode. The frontend performs the
    /// cook step before compiling the runtime.
    Play,
    /// Stop play mode and return to edit preview.
    Stop,
    /// Re-cook/rebuild/reload while play mode is already active.
    Rebuild,
    /// Build the current project and export the resulting EXE to the
    /// launcher Projects list. The frontend performs the cook step
    /// first, then compiles the runtime.
    BuildProject,
    /// The playable viewport was clicked; capture game input there.
    CaptureInput,
    /// Begin recording the pad state applied to embedded Play.
    StartInputRecording,
    /// Stop recording and save the current embedded Play tape.
    StopInputRecording,
    /// Replay the saved embedded Play input tape.
    StartInputReplay,
    /// Stop input replay and return to live input.
    StopInputReplay,
    /// Write the rolling embedded Play profiler history to the project logs.
    DumpProfilerHistory,
}

/// Frontend-owned embedded playtest state, mirrored into the editor
/// for toolbar labels and the playable viewport overlay.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EditorPlaytestStatus {
    /// No active or recent play mode.
    #[default]
    Idle,
    /// The active project is being cooked.
    Cooking,
    /// `make build-editor-playtest` is running in the frontend.
    Building,
    /// The editor viewport is showing the live in-process emulator.
    Running { input_captured: bool },
    /// The last embedded play attempt failed.
    Failed,
}

impl EditorPlaytestStatus {
    /// True while a Play / Stop pair should be offered.
    pub const fn is_active(self) -> bool {
        matches!(self, Self::Cooking | Self::Building | Self::Running { .. })
    }

    /// True when the 3D viewport should render the live game output.
    pub const fn is_playing(self) -> bool {
        matches!(self, Self::Running { .. })
    }
}

/// What the 3D editor viewport should paint this frame.
#[derive(Clone)]
pub struct EditorViewport3dPresentation {
    /// Egui texture to paint into the 3D viewport.
    pub texture: egui::TextureId,
    /// UV region inside `texture`.
    pub uv: Rect,
    /// Whether this is the editable preview or embedded play output.
    pub mode: EditorViewport3dMode,
    /// Editor-only screen-space overlays, in `overlay_source_size`
    /// coordinates. Kept out of the PSX-style preview command log so
    /// editor affordances can use host UI strokes, alpha, and
    /// fractional widths.
    pub overlay_lines: Vec<EditorViewportOverlayLine>,
    /// Logical source rectangle for `overlay_lines`.
    pub overlay_source_size: Vec2,
    /// Frontend-profiler metrics for live embedded play. These are
    /// emulator measurements, not egui repaint cadence.
    pub play_metrics: Option<EditorPlaytestMetrics>,
    /// Current embedded-play input tape state.
    pub play_tape: EditorPlaytestTapeStatus,
}

impl EditorViewport3dPresentation {
    /// Editable 3D preview generated by the editor preview renderer.
    pub fn edit(texture: egui::TextureId, overlay_lines: Vec<EditorViewportOverlayLine>) -> Self {
        Self {
            texture,
            uv: Rect::from_min_max(
                egui::pos2(0.0, 0.0),
                egui::pos2(640.0 / 2048.0, 480.0 / 1024.0),
            ),
            mode: EditorViewport3dMode::Edit,
            overlay_lines,
            overlay_source_size: egui::vec2(320.0, 240.0),
            play_metrics: None,
            play_tape: EditorPlaytestTapeStatus::default(),
        }
    }

    /// Live game output generated by the frontend emulator.
    pub fn play(
        texture: egui::TextureId,
        uv: Rect,
        play_tape: EditorPlaytestTapeStatus,
        play_metrics: Option<EditorPlaytestMetrics>,
    ) -> Self {
        Self {
            texture,
            uv,
            mode: EditorViewport3dMode::Play,
            overlay_lines: Vec::new(),
            overlay_source_size: Vec2::ZERO,
            play_metrics,
            play_tape,
        }
    }
}

/// Current mode for the embedded Play input tape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EditorPlaytestTapeMode {
    /// Live host input is driving the game.
    #[default]
    Idle,
    /// Live input is being appended to a tape.
    Recording,
    /// Saved tape input is driving the game.
    Replaying,
}

/// Editor-facing summary of the current input tape.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct EditorPlaytestTapeStatus {
    /// Current tape mode.
    pub mode: EditorPlaytestTapeMode,
    /// Number of recorded frames in the active tape.
    pub frames: u32,
    /// Current replay cursor, in frames.
    pub cursor: u32,
}

/// Rolling emulator metrics shown over the live editor Play viewport.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorPlaytestMetrics {
    /// Frontend profiler redraw sample id.
    pub sample_serial: u32,
    /// Host redraw rate from the frontend profiler.
    pub host_fps: f32,
    /// Average host frame time.
    pub host_ms: f32,
    /// Emulated VBlank rate per host second.
    pub emu_hz: f32,
    /// Paced visual frames produced by instrumented playtest builds.
    pub visual_hz: Option<f32>,
    /// VBlanks that produced draw traffic per guest refresh.
    pub draw_hz: f32,
    /// Visual frames emitted by the most recent frontend redraw.
    pub visual_frames: u32,
    /// Guest VBlank interval per paced visual frame.
    pub visual_interval_vblanks: f32,
    /// Guest visual deadline misses emitted by the most recent frontend redraw.
    pub visual_deadline_misses: u32,
    /// Maximum guest visual lateness emitted by the most recent frontend redraw.
    pub visual_lateness_vblanks: u32,
    /// Full frontend frame cost.
    pub total_ms: f32,
    /// Estimated visual-frame interval, derived from the current visual cadence.
    pub frame_ms: f32,
    /// Guest execution cost.
    pub emu_ms: f32,
    /// Hardware renderer cost.
    pub hw_ms: f32,
    /// egui/wgpu UI cost.
    pub ui_ms: f32,
    /// Guest cycle budget consumed by stepped frames.
    pub step_budget_percent: f32,
    /// Active room/chunk records submitted by the runtime renderer.
    pub chunk_visible: u32,
    /// Resident streamed room/chunk slots currently loaded.
    pub chunk_loaded: u32,
    /// Candidate chunks found by the active-room window builder.
    pub chunk_candidates: u32,
    /// Chunks built by the most recent active-room window rebuild.
    pub chunk_built: u32,
    /// Candidate chunks skipped because the active room cache was not ready.
    pub chunk_cache_skips: u32,
    /// Runtime rooms accepted by portal traversal.
    pub portal_visible_rooms: u32,
    /// Portal-clipped rooms beyond the traversal depth/capacity edge.
    pub portal_frontier_rooms: u32,
    /// Portal-visible rooms neither resident nor loading when the active window was built.
    pub portal_missing_resident: u32,
    /// Portal-visible rooms resident in stream cache but not buildable.
    pub portal_build_failed: u32,
    /// Directed portals tested by the runtime traversal.
    pub portal_tests: u32,
    /// Directed portals accepted by the runtime traversal.
    pub portal_accepts: u32,
    /// Directed portals recovered by occupied-room-bounds fallback.
    pub portal_bounds_fallbacks: u32,
    /// Portal rejections from backface, frustum, and tiny-cone tests.
    pub portal_rejects: [u32; 3],
    /// Portal traversal capacity hits for rooms, frustums, and depth.
    pub portal_caps: [u32; 3],
    /// Stream request priorities for current, visible, and frontier rooms.
    pub stream_priorities: [u32; 3],
    /// Stream scheduler requests considered by recent window refreshes.
    pub stream_requests: u32,
    /// Stream scheduler requests that were missing from resident slots.
    pub stream_misses: u32,
    /// Prefetch-only stream scheduler requests.
    pub stream_prefetches: u32,
    /// Resident stream slots evicted by recent window refreshes.
    pub stream_evictions: u32,
    /// Effective resident stream slot limit for the latest active window.
    pub stream_slot_limit: u32,
    /// Stream loads currently pending.
    pub stream_pending: u32,
    /// Stream loads that failed validation or CD reads.
    pub stream_failed: u32,
    /// Resident streamed chunks, keyed by runtime room/chunk index.
    pub chunk_loaded_mask: u64,
    /// Streamed chunks with in-flight loads, keyed by runtime room/chunk index.
    pub chunk_loading_mask: u64,
    /// Active drawable chunks, keyed by runtime room/chunk index.
    pub chunk_active_mask: u64,
    /// Chunks that submitted room geometry, keyed by runtime room/chunk index.
    pub chunk_drawn_mask: u64,
    /// Portal-accepted rooms, keyed by runtime room index.
    pub portal_visible_mask: u64,
    /// Portal depth/capacity frontier rooms, keyed by runtime room index.
    pub portal_frontier_mask: u64,
    /// Portal-accepted rooms missing residency and not loading, keyed by runtime room index.
    pub portal_missing_mask: u64,
    /// Portal-accepted resident rooms that failed active-room build.
    pub portal_build_failed_mask: u64,
    /// Destination rooms whose portals were tested by the latest traversal.
    pub portal_tested_mask: u64,
    /// Destination rooms whose portals were accepted by the latest traversal.
    pub portal_accepted_mask: u64,
    /// Destination rooms rejected by portal window clipping in the latest traversal.
    pub portal_reject_frustum_mask: u64,
    /// Destination rooms recovered by occupied-room-bounds fallback in the latest traversal.
    pub portal_bounds_fallback_mask: u64,
    /// Directed portal records tested in the latest traversal.
    pub portal_tested_portal_mask: u64,
    /// Directed portal records accepted in the latest traversal.
    pub portal_accepted_portal_mask: u64,
    /// Directed portal records rejected by camera/window clipping.
    pub portal_reject_frustum_portal_mask: u64,
    /// Directed portal records recovered by occupied-room-bounds fallback.
    pub portal_bounds_fallback_portal_mask: u64,
    /// True when the profiler sample contains player map telemetry.
    pub player_map_valid: bool,
    /// Runtime room/chunk index containing the player.
    pub player_room_index: u32,
    /// Runtime room/chunk index used as the root of portal traversal.
    pub portal_current_room_index: u32,
    /// Player room-local X in engine units.
    pub player_local_x: i32,
    /// Player room-local Z in engine units.
    pub player_local_z: i32,
    /// Camera/view yaw in Q12 angle units for player-centred chunk diagnostics.
    pub player_view_yaw_q12: u16,
    /// True when the profiler sample contains exact render-camera yaw basis telemetry.
    pub camera_view_basis_valid: bool,
    /// Render camera yaw sine in Q12 basis units.
    pub camera_view_sin_yaw_q12: i32,
    /// Render camera yaw cosine in Q12 basis units.
    pub camera_view_cos_yaw_q12: i32,
    /// Render camera pitch sine in Q12 basis units.
    pub camera_view_sin_pitch_q12: i32,
    /// Render camera pitch cosine in Q12 basis units.
    pub camera_view_cos_pitch_q12: i32,
    /// True when the profiler sample contains render-camera map telemetry.
    pub camera_map_valid: bool,
    /// True when the profiler sample contains exact level-space render-camera telemetry.
    pub camera_global_valid: bool,
    /// Render camera room-local X in engine units.
    pub camera_local_x: i32,
    /// Render camera room-local Y in engine units.
    pub camera_local_y: i32,
    /// Render camera room-local Z in engine units.
    pub camera_local_z: i32,
    /// Render camera absolute level X in engine units.
    pub camera_global_x: i32,
    /// Render camera absolute level Y in engine units.
    pub camera_global_y: i32,
    /// Render camera absolute level Z in engine units.
    pub camera_global_z: i32,
}

/// One host-drawn editor overlay segment over the 3D preview.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorViewportOverlayLine {
    pub a: Pos2,
    pub b: Pos2,
    pub color: Color32,
    pub width: f32,
}

impl EditorViewportOverlayLine {
    pub const fn new(a: Pos2, b: Pos2, color: Color32, width: f32) -> Self {
        Self { a, b, color, width }
    }
}

/// Mode for the 3D viewport presentation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EditorViewport3dMode {
    /// Editable authoring preview.
    Edit,
    /// Embedded emulator framebuffer.
    Play,
}
