//! Public embedded-play viewport API shared with the frontend.

use egui::{Color32, Pos2, Rect, Vec2};

/// Request emitted by the editor UI for embedded play mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EditorPlaytestRequest {
    /// Cook/build/load and start play mode.
    Play,
    /// Stop play mode and return to edit preview.
    Stop,
    /// Re-cook/rebuild/reload while play mode is already active.
    Rebuild,
    /// Cook/build the current project and export the resulting EXE to
    /// the launcher Projects list.
    BakeProjectBuild,
    /// The playable viewport was clicked; capture game input there.
    CaptureInput,
}

/// Frontend-owned embedded playtest state, mirrored into the editor
/// for toolbar labels and the playable viewport overlay.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum EditorPlaytestStatus {
    /// No active or recent play mode.
    #[default]
    Idle,
    /// The active project is being cooked.
    Cooking,
    /// `make build-editor-playtest` is running in the frontend.
    Building,
    /// The editor viewport is showing the live in-process emulator.
    Running { input_captured: bool },
    /// The last embedded play attempt failed.
    Failed,
}

impl EditorPlaytestStatus {
    /// True while a Play / Stop pair should be offered.
    pub const fn is_active(self) -> bool {
        matches!(self, Self::Cooking | Self::Building | Self::Running { .. })
    }

    /// True when the 3D viewport should render the live game output.
    pub const fn is_playing(self) -> bool {
        matches!(self, Self::Running { .. })
    }
}

/// What the 3D editor viewport should paint this frame.
#[derive(Clone)]
pub struct EditorViewport3dPresentation {
    /// Egui texture to paint into the 3D viewport.
    pub texture: egui::TextureId,
    /// UV region inside `texture`.
    pub uv: Rect,
    /// Whether this is the editable preview or embedded play output.
    pub mode: EditorViewport3dMode,
    /// Editor-only screen-space overlays, in `overlay_source_size`
    /// coordinates. Kept out of the PSX-style preview command log so
    /// editor affordances can use host UI strokes, alpha, and
    /// fractional widths.
    pub overlay_lines: Vec<EditorViewportOverlayLine>,
    /// Logical source rectangle for `overlay_lines`.
    pub overlay_source_size: Vec2,
}

impl EditorViewport3dPresentation {
    /// Editable 3D preview generated by the editor preview renderer.
    pub fn edit(texture: egui::TextureId, overlay_lines: Vec<EditorViewportOverlayLine>) -> Self {
        Self {
            texture,
            uv: Rect::from_min_max(
                egui::pos2(0.0, 0.0),
                egui::pos2(640.0 / 2048.0, 480.0 / 1024.0),
            ),
            mode: EditorViewport3dMode::Edit,
            overlay_lines,
            overlay_source_size: egui::vec2(320.0, 240.0),
        }
    }

    /// Live game output generated by the frontend emulator.
    pub fn play(texture: egui::TextureId, uv: Rect) -> Self {
        Self {
            texture,
            uv,
            mode: EditorViewport3dMode::Play,
            overlay_lines: Vec::new(),
            overlay_source_size: Vec2::ZERO,
        }
    }
}

/// One host-drawn editor overlay segment over the 3D preview.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct EditorViewportOverlayLine {
    pub a: Pos2,
    pub b: Pos2,
    pub color: Color32,
    pub width: f32,
}

impl EditorViewportOverlayLine {
    pub const fn new(a: Pos2, b: Pos2, color: Color32, width: f32) -> Self {
        Self { a, b, color, width }
    }
}

/// Mode for the 3D viewport presentation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EditorViewport3dMode {
    /// Editable authoring preview.
    Edit,
    /// Embedded emulator framebuffer.
    Play,
}
