#!/usr/bin/env python3
"""Verify actual guest encounter traces generated by replay.py, without third-party packages."""
import csv
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / 'validation/enemy-behavior'

def read(case):
    with (OUT / f'{case}.trace.csv').open() as source:
        return [{key: int(value) for key, value in row.items()} for row in csv.DictReader(source)]

def verify():
    traces = {case: read(case) for case in ('reset', 'blocked', 'circle', 'retreat')}
    assert all(len(rows) >= 150 for rows in traces.values()), 'Missing guest samples'
    reset = {row['tick']: row for row in traces['reset']}
    pairs = [(row, reset[row['tick'] + 900]) for row in reset.values()
             if 360 <= row['tick'] < 1260 and row['tick'] + 900 in reset]
    assert len(pairs) >= 70, 'Missing reset comparison interval'
    differences = [a['tick'] for a, b in pairs if
                   any(a[key] != b[key] for key in a if key != 'tick')]
    assert not differences, f'Reset diverged at ticks {differences}'

    rows = [row for values in traces.values() for row in values if row['tick'] >= 372]
    goals = sorted({row['goal'] for row in rows})
    assert set(range(9)) <= set(goals), f'Movement goal coverage incomplete: {goals}'
    combat_clips = {row['clip'] for row in rows if row['state'] == 4}
    assert {0, 12, 13} <= combat_clips, f'Missing cannon/heavy/light attacks: {combat_clips}'
    assert {2, 3} <= {row['clip'] for row in rows if row['state'] == 2}, 'Missing walk/run'

    blocked = [row for row in traces['blocked'] if row['tick'] >= 372]
    assert {6, 7, 8} <= {row['goal'] for row in blocked}, 'Missing physical recovery sequence'
    assert all(224 <= row['enemy_x'] <= 288 and -160 <= row['enemy_z'] <= -96
               and row['enemy_y'] == 0 for row in blocked), 'Enemy crossed the sealed pen'
    assert max(row['retries'] for row in blocked) >= 3, 'Failure did not escalate'

    retreat = [row for row in traces['retreat'] if row['tick'] >= 372]
    home = [row for row in retreat if row['goal'] == 8]
    assert len(home) >= 10, 'No sustained physical return'
    last = retreat[-1]
    assert last['state'] == 0 and last['result'] == 1, 'Return did not finish with idle/arrival'
    assert max(abs(last['enemy_x']), abs(last['enemy_z'])) <= 14, 'Enemy did not reach spawn'
    assert len({(row['enemy_x'], row['enemy_z']) for row in home}) >= 10, 'Home did not move'
    for a, b in zip(retreat, retreat[1:]):
        dt = b['tick'] - a['tick']
        assert max(abs(b['enemy_x'] - a['enemy_x']), abs(b['enemy_z'] - a['enemy_z'])) <= dt * 6 + 2, 'Unexpected teleport'

    report = {'passed': True, 'samples': {key: len(value) for key, value in traces.items()},
              'identical_reset_checkpoints': len(pairs), 'reset_mismatches': differences,
              'observed_goals': goals, 'combat_clips': sorted(combat_clips),
              'blocked_max_retries': max(row['retries'] for row in blocked),
              'home_movement_samples': len(home),
              'home_final_position': [last[f'enemy_{axis}'] for axis in 'xyz']}
    (OUT / 'verification.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report, indent=2))

if __name__ == '__main__':
    verify()
