//! Shared `no_std` level manifest schema.
//!
//! Generated by the editor's playtest compiler ([`psxed_project::playtest`])
//! and consumed by the editor-playtest runtime example. The records here
//! describe a level the runtime can resolve through a real residency
//! contract (master asset table, per-room residency lists) -- the
//! current backing store is `include_bytes!`, but the same schema
//! is what future stream-pack / CD-streaming code will resolve
//! against.
//!
//! # Scope
//!
//! Only the records that are *both written by the editor compiler
//! and consumed by the runtime in this same pass* live here. No
//! speculative future systems (portals, PVS, farfield, lighting,
//! actors, audio banks) -- they land alongside the writer + reader
//! that need them.
//!
//! # `no_std`
//!
//! Built without `alloc`. Records are POD-style with `&'static`
//! borrows: the generated source emits `&'static [u8]` /
//! `&'static [AssetId]` slices that the linker pins next to the
//! `include_bytes!` data. Heap-free by construction.

#![no_std]
#![warn(missing_docs)]

/// Stable identifier assigned to every level asset by the editor
/// compiler. `AssetId` values are deterministic across runs:
/// rooms first (in scene-tree order), then textures (ordered by
/// first use in cooked material slot order).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct AssetId(pub u16);

macro_rules! typed_index {
    ($(#[$meta:meta])* pub struct $name:ident;) => {
        $(#[$meta])*
        #[repr(transparent)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(pub u16);

        impl $name {
            /// Zero index.
            pub const ZERO: Self = Self(0);

            /// Build from raw manifest storage.
            pub const fn new(raw: u16) -> Self {
                Self(raw)
            }

            /// Return raw manifest storage.
            pub const fn raw(self) -> u16 {
                self.0
            }

            /// Convert to `usize` for slice indexing.
            pub const fn to_usize(self) -> usize {
                self.0 as usize
            }
        }
    };
}

typed_index! {
    /// Index into the generated `ROOMS` table.
    pub struct RoomIndex;
}

typed_index! {
    /// Index into the generated `MATERIALS` table.
    pub struct MaterialIndex;
}

typed_index! {
    /// Local material slot stored inside a cooked `.psxw` face.
    pub struct MaterialSlot;
}

typed_index! {
    /// Index into the generated `MODELS` table.
    pub struct ModelIndex;
}

typed_index! {
    /// Index into the generated global `MODEL_CLIPS` table.
    pub struct ModelClipTableIndex;
}

typed_index! {
    /// Clip index local to one model's clip slice.
    pub struct ModelClipIndex;
}

typed_index! {
    /// Index into the generated `CHARACTERS` table.
    pub struct CharacterIndex;
}

typed_index! {
    /// Runtime resource slot for entity records.
    pub struct ResourceSlot;
}

/// Optional local model-clip index.
///
/// Used for both "no authored clip" character fields and "inherit
/// the model default" model-instance fields. The named constants keep
/// those call sites readable while preserving the compact `u16`
/// manifest representation.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct OptionalModelClipIndex(pub u16);

impl OptionalModelClipIndex {
    /// Sentinel for "no clip authored".
    pub const NONE: Self = Self(u16::MAX);
    /// Sentinel for "inherit the owning model's default clip".
    pub const INHERIT: Self = Self(u16::MAX);

    /// Build an optional value that contains a local clip index.
    pub const fn some(index: ModelClipIndex) -> Self {
        Self(index.raw())
    }

    /// Build directly from raw manifest storage.
    pub const fn from_raw(raw: u16) -> Self {
        Self(raw)
    }

    /// Return raw manifest storage.
    pub const fn raw(self) -> u16 {
        self.0
    }

    /// Return `true` when a real local clip index is present.
    pub const fn is_some(self) -> bool {
        self.0 != u16::MAX
    }

    /// Return `true` when this stores the sentinel value.
    pub const fn is_none(self) -> bool {
        self.0 == u16::MAX
    }

    /// Convert to a local clip index if present.
    pub const fn to_option(self) -> Option<ModelClipIndex> {
        if self.is_some() {
            Some(ModelClipIndex(self.0))
        } else {
            None
        }
    }

    /// Return the contained clip index, or `fallback` for the sentinel.
    pub const fn unwrap_or(self, fallback: ModelClipIndex) -> ModelClipIndex {
        match self.to_option() {
            Some(index) => index,
            None => fallback,
        }
    }
}

/// Coarse asset class -- the runtime branches on this to pick a
/// loader (`World::from_bytes` for rooms, `Texture::from_bytes`
/// for textures). Restricted to the variants generated *and*
/// consumed in this pass; future kinds (`ActorModel`,
/// `LightSet`, `FarfieldCard`, `AudioBank`, …) land when both
/// sides exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssetKind {
    /// Cooked `.psxw` room blob.
    RoomWorld,
    /// Cooked `.psxt` texture blob (room material atlas, model
    /// atlas, etc -- any cooked indexed-colour PSX texture).
    Texture,
    /// Cooked `.psxmdl` animated/static model blob, bound to a
    /// model atlas asset and any number of clip assets.
    ModelMesh,
    /// Cooked `.psxanim` skeletal animation clip -- references
    /// joint count + frames matching its owning model.
    ModelAnimation,
}

/// One asset in the master table. The byte slice is the live
/// payload -- `include_bytes!` today, a stream-pack offset later.
/// `ram_bytes` and `vram_bytes` are budget hints the residency
/// manager can use to refuse oversize bind sets without parsing
/// the payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelAssetRecord {
    /// Stable id assigned by the compiler.
    pub id: AssetId,
    /// Asset class -- picks the loader.
    pub kind: AssetKind,
    /// Backing payload. For `include_bytes!`-baked assets this
    /// points into the EXE; for future stream packs this will be
    /// the live in-memory slice once the pack is paged in.
    pub bytes: &'static [u8],
    /// RAM cost in bytes. For embedded assets this equals
    /// `bytes.len()`; a stream pack would report the asset's
    /// in-RAM size after decompression.
    pub ram_bytes: u32,
    /// VRAM cost in bytes if this asset uploads to VRAM
    /// (textures). `0` for RAM-only assets (room worlds).
    pub vram_bytes: u32,
    /// Reserved.
    pub flags: u16,
}

/// One room. References its world asset by id and points into
/// the global [`LevelMaterialRecord`] table via
/// `material_first` / `material_count`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelRoomRecord {
    /// Display name -- surfaces in editor logs / debug HUDs.
    pub name: &'static str,
    /// Cooked `.psxw` asset.
    pub world_asset: AssetId,
    /// Editor-side origin X (sectors). Diagnostic only -- the
    /// cooker normalizes geometry to be array-rooted.
    pub origin_x: i32,
    /// Editor-side origin Z.
    pub origin_z: i32,
    /// Engine units per sector.
    pub sector_size: i32,
    /// First index into the global `MATERIALS` table for this
    /// room's material slice.
    pub material_first: MaterialIndex,
    /// Number of `LevelMaterialRecord`s in this room's slice.
    /// Matches the cooked `.psxw`'s material count.
    pub material_count: u16,
    /// Reserved.
    pub flags: u16,
}

/// One material slot for one room. The compiler emits records
/// in `(room, local_slot)` order; the runtime walks the room's
/// slice and binds `local_slot` → `texture_asset` into a
/// `TextureMaterial` table indexed by the cooked face's stored
/// material slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelMaterialRecord {
    /// Owning room index in [`LevelRoomRecord`] order.
    pub room: RoomIndex,
    /// Cooked-world local material slot. Matches the value the
    /// `.psxw` stores per-face / per-wall.
    pub local_slot: MaterialSlot,
    /// Texture asset bound at this slot.
    pub texture_asset: AssetId,
    /// Per-material modulation tint. Renderer multiplies the
    /// texture sample by this colour.
    pub tint_rgb: [u8; 3],
    /// Runtime material flags. Low two bits encode face sidedness
    /// using [`material_flags::FACE_*`].
    pub flags: u16,
}

/// Material flag bits stored in [`LevelMaterialRecord::flags`].
pub mod material_flags {
    /// Mask for the face-sidedness bits.
    pub const FACE_MASK: u16 = 0x0003;
    /// Draw only the authored front side.
    pub const FACE_FRONT: u16 = 0x0000;
    /// Draw only the opposite side.
    pub const FACE_BACK: u16 = 0x0001;
    /// Draw either winding.
    pub const FACE_BOTH: u16 = 0x0002;
}

/// Which side of a room face should render.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LevelMaterialSidedness {
    /// Authored/front winding only.
    Front,
    /// Opposite winding only.
    Back,
    /// No winding cull.
    Both,
}

impl LevelMaterialRecord {
    /// Decode the material's face-sidedness flags.
    pub const fn sidedness(self) -> LevelMaterialSidedness {
        match self.flags & material_flags::FACE_MASK {
            material_flags::FACE_BACK => LevelMaterialSidedness::Back,
            material_flags::FACE_BOTH => LevelMaterialSidedness::Both,
            _ => LevelMaterialSidedness::Front,
        }
    }
}

/// Per-room residency contract. The runtime calls
/// `ResidencyManager::ensure_room_resident` with this record on
/// room enter; it lists exactly the assets that must be in RAM
/// and VRAM before the room can render.
///
/// `warm_*` lists are placeholders for future preload hints
/// (neighbour rooms, soon-to-be-streamed assets). They're
/// always empty in this pass.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RoomResidencyRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Assets that must be RAM-resident before render.
    pub required_ram: &'static [AssetId],
    /// Assets that must be VRAM-resident (uploaded textures).
    pub required_vram: &'static [AssetId],
    /// Preload-hint assets that *should* be RAM-resident soon
    /// (e.g. neighbour rooms across an open portal). Empty in
    /// this pass.
    pub warm_ram: &'static [AssetId],
    /// Same idea for VRAM. Empty in this pass.
    pub warm_vram: &'static [AssetId],
}

/// Player spawn point. Coordinates are room-local engine units
/// (the same space the cooked `.psxw` lives in -- array-rooted
/// at world `(0, 0)`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlayerSpawnRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Room-local X.
    pub x: i32,
    /// Y (typically 0 for floor-anchored spawns).
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Yaw in PSX angle units (`0..4096`).
    pub yaw: i16,
    /// Reserved. Bit 0 = "spawn enabled" by current writer.
    pub flags: u16,
}

/// Coarse runtime kind for [`EntityRecord`]. Markers are
/// visual debug stubs (cubes); `StaticMesh` will reference a
/// resource slot once the asset pipeline supports meshes as
/// `LevelAssetRecord`s.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntityKind {
    /// Visual marker (debug cube).
    Marker,
    /// Static mesh instance pinned by `resource_slot`.
    StaticMesh,
}

/// One non-spawn entity. Same room-local coordinate convention
/// as [`PlayerSpawnRecord`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EntityRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Entity kind.
    pub kind: EntityKind,
    /// Room-local X.
    pub x: i32,
    /// Y.
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Yaw, PSX angle units.
    pub yaw: i16,
    /// Resource slot (0 if unused -- e.g. for `Marker`).
    pub resource_slot: ResourceSlot,
    /// Reserved.
    pub flags: u16,
}

/// One animation clip bound to a [`LevelModelRecord`]. The clip
/// asset's joint count is checked against the owning model's
/// joint count at cook time; runtime trusts the contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelClipRecord {
    /// Owning model index in [`LevelModelRecord`] order.
    pub model: ModelIndex,
    /// Display name -- surfaces in editor logs / debug HUDs.
    pub name: &'static str,
    /// Cooked `.psxanim` asset.
    pub animation_asset: AssetId,
}

/// One cooked PSX model: `.psxmdl` mesh, optional `.psxt`
/// atlas, and a slice of clips. Instances reference this record
/// by index via [`LevelModelInstanceRecord::model`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelRecord {
    /// Display name.
    pub name: &'static str,
    /// Cooked `.psxmdl` asset.
    pub mesh_asset: AssetId,
    /// Atlas texture asset. The schema keeps this `Option` for
    /// future flat-shaded / untextured model paths, but the
    /// playtest cooker rejects placed instances of any model
    /// without an atlas -- the runtime model path renders
    /// textured animated models only.
    pub texture_asset: Option<AssetId>,
    /// First index into the global `MODEL_CLIPS` table.
    pub clip_first: ModelClipTableIndex,
    /// Number of clips in this model's slice.
    pub clip_count: u16,
    /// Default clip index *within this model's slice* -- runtime
    /// instances with no per-instance override pick this clip.
    /// Cooker validation guarantees this resolves to a valid
    /// clip; the runtime never has to fall back to bind pose
    /// (no bind-pose path exists in this pass).
    pub default_clip: ModelClipIndex,
    /// Suggested world-space height (engine units) -- mirrors
    /// the `.psxmdl` header's `local_to_world` hint.
    pub world_height: u16,
    /// Reserved.
    pub flags: u16,
}

/// One placed model instance. Coordinates are room-local
/// engine units. `clip` is an index into the owning model's
/// clip slice; `0xFFFF` means "use the model's `default_clip`".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelInstanceRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Model index in [`LevelModelRecord`] order.
    pub model: ModelIndex,
    /// Per-instance clip override, or `0xFFFF` to inherit the
    /// model's `default_clip`.
    pub clip: OptionalModelClipIndex,
    /// Room-local X.
    pub x: i32,
    /// Y.
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Yaw, PSX angle units.
    pub yaw: i16,
    /// Reserved.
    pub flags: u16,
}

/// Sentinel for [`LevelModelInstanceRecord::clip`] meaning
/// "inherit model default".
pub const MODEL_CLIP_INHERIT: OptionalModelClipIndex = OptionalModelClipIndex::INHERIT;

/// One placed point light. Coordinates are room-local engine
/// units (same convention as model instances and player
/// spawn). Lighting model is dynamic point-light only -- no
/// shadows, no baked lightmaps. Both editor and runtime
/// accumulate per-surface contribution from every record in
/// the same room and clamp to 8-bit RGB.
///
/// `intensity_q8` is the multiplier in Q8.8 fixed-point
/// (256 = 1.0, 512 = 2.0, ...); the cooker derives it from
/// the editor's `f32` intensity field so the host UI keeps
/// floats while the wire format stays integer-only. `radius`
/// is engine units; surfaces past the radius receive zero
/// contribution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PointLightRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Room-local X.
    pub x: i32,
    /// Y.
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Cutoff distance in engine units. Surfaces beyond this
    /// receive zero contribution. Cooker rejects `0`.
    pub radius: u16,
    /// Brightness multiplier, Q8.8. `256` = 1.0.
    pub intensity_q8: u16,
    /// 8-bit RGB tint applied before the per-surface
    /// attenuation weight.
    pub color: [u8; 3],
    /// Reserved.
    pub flags: u16,
}

/// Sentinel for optional [`LevelCharacterRecord`] clip slots
/// (`run_clip` / `turn_clip`). The runtime treats this as
/// "no clip authored for this role" and falls back to walk /
/// idle as appropriate.
pub const CHARACTER_CLIP_NONE: OptionalModelClipIndex = OptionalModelClipIndex::NONE;

/// Gameplay character -- backing model + role-clip mapping +
/// capsule / camera / controller defaults. Layered on top of
/// a [`LevelModelRecord`]; the player spawn references one of
/// these via [`PlayerControllerRecord::character`] to resolve
/// what to render and how the controller behaves.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCharacterRecord {
    /// Index into [`LevelModelRecord`] this character renders
    /// as. The cooker guarantees this resolves; runtime trusts
    /// the contract.
    pub model: ModelIndex,
    /// Idle clip index *within the model's clip slice*. The
    /// cooker rejects characters whose idle clip is out of
    /// range -- runtime never has to fall back to bind pose.
    pub idle_clip: ModelClipIndex,
    /// Walk clip index within the model's clip slice. Required
    /// (same validation as `idle_clip`).
    pub walk_clip: ModelClipIndex,
    /// Optional run clip index. [`CHARACTER_CLIP_NONE`] means
    /// "no run clip authored -- runtime should fall back to
    /// `walk_clip` when the controller wants to run".
    pub run_clip: OptionalModelClipIndex,
    /// Optional turn clip index. Same sentinel as `run_clip`.
    pub turn_clip: OptionalModelClipIndex,
    /// Capsule radius in engine units. Used by collision +
    /// any future debug draw.
    pub radius: u16,
    /// Capsule height in engine units.
    pub height: u16,
    /// Forward walk speed (engine units per 60 Hz frame).
    pub walk_speed: i32,
    /// Forward run speed (engine units per 60 Hz frame).
    pub run_speed: i32,
    /// Yaw rate the controller applies when turning.
    pub turn_speed_degrees_per_second: u16,
    /// Distance the third-person camera trails the character.
    pub camera_distance: i32,
    /// Camera vertical offset above the character origin.
    pub camera_height: i32,
    /// Vertical offset of the camera's look-at target above
    /// the character origin.
    pub camera_target_height: i32,
    /// Reserved.
    pub flags: u16,
}

/// Player-controller record: which spawn the player starts at
/// and which character drives them. Generated as a single
/// optional record in the manifest -- `Some` when a player
/// spawn was authored, `None` for headless / preview manifests.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlayerControllerRecord {
    /// Resolved spawn -- same struct the manifest already emits
    /// as a top-level `PLAYER_SPAWN`. Embedded here so the
    /// runtime can look at one record to bring up the player.
    pub spawn: PlayerSpawnRecord,
    /// Index into [`LevelCharacterRecord`] driving the player.
    pub character: CharacterIndex,
    /// Reserved.
    pub flags: u16,
}

/// Linear scan over the master asset table. `O(n)` is fine for
/// the asset counts this pass targets (few rooms × handful of
/// textures); a binary search lands when manifests grow.
pub fn find_asset(
    assets: &'static [LevelAssetRecord],
    id: AssetId,
) -> Option<&'static LevelAssetRecord> {
    let mut i = 0;
    while i < assets.len() {
        if assets[i].id == id {
            return Some(&assets[i]);
        }
        i += 1;
    }
    None
}

/// Like [`find_asset`] but also asserts the asset has the
/// expected kind. Use this when you're about to feed bytes to
/// a kind-specific loader (`World::from_bytes`, etc.) -- picks
/// up manifest typos that would otherwise crash inside the
/// loader.
pub fn find_asset_of_kind(
    assets: &'static [LevelAssetRecord],
    id: AssetId,
    kind: AssetKind,
) -> Option<&'static LevelAssetRecord> {
    let asset = find_asset(assets, id)?;
    if asset.kind == kind {
        Some(asset)
    } else {
        None
    }
}

/// Snapshot of one `ensure_room_resident` call. Lets the caller
/// log how many assets actually moved (vs. were already
/// resident) without re-scanning the residency lists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ResidencyChangeSet {
    /// Required RAM assets that weren't resident before this
    /// call (i.e. would have been faulted in).
    pub missing_ram_count: u16,
    /// Required VRAM assets that weren't resident before this
    /// call.
    pub missing_vram_count: u16,
    /// Required RAM assets already present.
    pub already_resident_ram_count: u16,
    /// Required VRAM assets already present.
    pub already_resident_vram_count: u16,
    /// Required RAM assets that didn't fit in the residency
    /// table (capacity exceeded).
    pub overflow_ram_count: u16,
    /// Required VRAM assets that didn't fit.
    pub overflow_vram_count: u16,
}

/// Tiny no-alloc residency tracker. Records which `AssetId`s
/// the runtime considers RAM- or VRAM-resident. Capacity is
/// fixed at compile time by `RAM_CAP` / `VRAM_CAP`; overflow
/// is reported through [`ResidencyChangeSet`] rather than
/// silently dropping assets.
///
/// This pass uses the manager only to avoid re-uploading
/// textures every frame -- eviction / LRU / stream-pack paging
/// land in later passes. RAM tracking is logical because every
/// asset is `include_bytes!`-resident from process start.
#[derive(Debug, Clone, Copy)]
pub struct ResidencyManager<const RAM_CAP: usize, const VRAM_CAP: usize> {
    ram: [Option<AssetId>; RAM_CAP],
    vram: [Option<AssetId>; VRAM_CAP],
}

impl<const RAM_CAP: usize, const VRAM_CAP: usize> Default for ResidencyManager<RAM_CAP, VRAM_CAP> {
    fn default() -> Self {
        Self::new()
    }
}

impl<const RAM_CAP: usize, const VRAM_CAP: usize> ResidencyManager<RAM_CAP, VRAM_CAP> {
    /// Empty manager. `const fn` so callers can build one in a
    /// `static` initializer if they want.
    pub const fn new() -> Self {
        Self {
            ram: [None; RAM_CAP],
            vram: [None; VRAM_CAP],
        }
    }

    /// `true` if `id` is RAM-resident.
    pub fn contains_ram(&self, id: AssetId) -> bool {
        contains(&self.ram, id)
    }

    /// `true` if `id` is VRAM-resident.
    pub fn contains_vram(&self, id: AssetId) -> bool {
        contains(&self.vram, id)
    }

    /// Mark `id` RAM-resident. Returns `true` on first insert,
    /// `false` if already present or the table is full.
    pub fn mark_ram_resident(&mut self, id: AssetId) -> bool {
        insert(&mut self.ram, id)
    }

    /// Mark `id` VRAM-resident. Returns `true` on first insert,
    /// `false` if already present or the table is full.
    pub fn mark_vram_resident(&mut self, id: AssetId) -> bool {
        insert(&mut self.vram, id)
    }

    /// Number of RAM slots in use.
    pub fn ram_len(&self) -> usize {
        self.ram.iter().filter(|s| s.is_some()).count()
    }

    /// Number of VRAM slots in use.
    pub fn vram_len(&self) -> usize {
        self.vram.iter().filter(|s| s.is_some()).count()
    }

    /// Run the residency contract for `room`: every required
    /// asset is marked resident; the returned change-set says
    /// which were already there, which were just brought in,
    /// and which couldn't fit. Caller is responsible for the
    /// actual upload (asset bytes → VRAM rect) for *missing*
    /// VRAM assets.
    pub fn ensure_room_resident(&mut self, room: &RoomResidencyRecord) -> ResidencyChangeSet {
        let mut cs = ResidencyChangeSet::default();
        for &id in room.required_ram {
            if self.contains_ram(id) {
                cs.already_resident_ram_count = cs.already_resident_ram_count.saturating_add(1);
            } else if self.mark_ram_resident(id) {
                cs.missing_ram_count = cs.missing_ram_count.saturating_add(1);
            } else {
                cs.overflow_ram_count = cs.overflow_ram_count.saturating_add(1);
            }
        }
        for &id in room.required_vram {
            if self.contains_vram(id) {
                cs.already_resident_vram_count = cs.already_resident_vram_count.saturating_add(1);
            } else if self.mark_vram_resident(id) {
                cs.missing_vram_count = cs.missing_vram_count.saturating_add(1);
            } else {
                cs.overflow_vram_count = cs.overflow_vram_count.saturating_add(1);
            }
        }
        cs
    }
}

fn contains<const N: usize>(slots: &[Option<AssetId>; N], id: AssetId) -> bool {
    let mut i = 0;
    while i < N {
        if let Some(existing) = slots[i] {
            if existing == id {
                return true;
            }
        }
        i += 1;
    }
    false
}

fn insert<const N: usize>(slots: &mut [Option<AssetId>; N], id: AssetId) -> bool {
    // First scan checks for duplicates so we don't claim two
    // slots for the same id; second scan finds the first free
    // slot. Callers that want "is resident" without inserting
    // call `contains` directly.
    let mut i = 0;
    while i < N {
        if let Some(existing) = slots[i] {
            if existing == id {
                return false;
            }
        }
        i += 1;
    }
    let mut i = 0;
    while i < N {
        if slots[i].is_none() {
            slots[i] = Some(id);
            return true;
        }
        i += 1;
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    static ROOM_BYTES: &[u8] = b"PSXW-stub";
    static TEX_BYTES: &[u8] = b"PSXT-stub";

    static ASSETS: &[LevelAssetRecord] = &[
        LevelAssetRecord {
            id: AssetId(0),
            kind: AssetKind::RoomWorld,
            bytes: ROOM_BYTES,
            ram_bytes: 9,
            vram_bytes: 0,
            flags: 0,
        },
        LevelAssetRecord {
            id: AssetId(1),
            kind: AssetKind::Texture,
            bytes: TEX_BYTES,
            ram_bytes: 9,
            vram_bytes: 16,
            flags: 0,
        },
    ];

    #[test]
    fn find_asset_returns_record_by_id() {
        assert_eq!(
            find_asset(ASSETS, AssetId(0)).map(|a| a.id),
            Some(AssetId(0))
        );
        assert_eq!(
            find_asset(ASSETS, AssetId(1)).map(|a| a.id),
            Some(AssetId(1))
        );
        assert!(find_asset(ASSETS, AssetId(42)).is_none());
    }

    #[test]
    fn find_asset_of_kind_filters_by_kind() {
        assert!(find_asset_of_kind(ASSETS, AssetId(0), AssetKind::RoomWorld).is_some());
        assert!(find_asset_of_kind(ASSETS, AssetId(0), AssetKind::Texture).is_none());
        assert!(find_asset_of_kind(ASSETS, AssetId(1), AssetKind::Texture).is_some());
    }

    #[test]
    fn residency_marks_missing_then_resident() {
        let mut r = ResidencyManager::<4, 4>::new();
        let room = RoomResidencyRecord {
            room: RoomIndex::ZERO,
            required_ram: &[AssetId(0)],
            required_vram: &[AssetId(1), AssetId(2)],
            warm_ram: &[],
            warm_vram: &[],
        };

        let first = r.ensure_room_resident(&room);
        assert_eq!(first.missing_ram_count, 1);
        assert_eq!(first.missing_vram_count, 2);
        assert_eq!(first.already_resident_ram_count, 0);
        assert_eq!(first.already_resident_vram_count, 0);

        let second = r.ensure_room_resident(&room);
        assert_eq!(second.missing_ram_count, 0);
        assert_eq!(second.missing_vram_count, 0);
        assert_eq!(second.already_resident_ram_count, 1);
        assert_eq!(second.already_resident_vram_count, 2);
    }

    #[test]
    fn duplicate_mark_returns_false() {
        let mut r = ResidencyManager::<4, 4>::new();
        assert!(r.mark_ram_resident(AssetId(7)));
        assert!(!r.mark_ram_resident(AssetId(7)));
        assert_eq!(r.ram_len(), 1);
    }

    #[test]
    fn residency_overflow_is_reported_not_silent() {
        let mut r = ResidencyManager::<2, 2>::new();
        let room = RoomResidencyRecord {
            room: RoomIndex::ZERO,
            required_ram: &[AssetId(1), AssetId(2), AssetId(3)],
            required_vram: &[],
            warm_ram: &[],
            warm_vram: &[],
        };
        let cs = r.ensure_room_resident(&room);
        assert_eq!(cs.missing_ram_count, 2);
        assert_eq!(cs.overflow_ram_count, 1);
        assert_eq!(r.ram_len(), 2);
    }
}
