//! Shared `no_std` level manifest schema.
//!
//! Generated by the editor's playtest compiler ([`psxed_project::playtest`])
//! and consumed by the editor-playtest runtime example. The records here
//! describe a level the runtime can resolve through a real residency
//! contract (master asset table, per-room residency lists) -- the
//! current backing store is `include_bytes!`, but the same schema
//! is what future stream-pack / CD-streaming code will resolve
//! against. Runtime-consumed visibility/PVS records live here too
//! because the playtest cooker now emits them and the PSX renderer
//! consumes them directly.
//!
//! # Scope
//!
//! Only the records that are *both written by the editor compiler
//! and consumed by the runtime in this same pass* live here. No
//! speculative future systems (farfield, actors, audio banks) --
//! they land alongside the writer + reader that need them.
//!
//! # `no_std`
//!
//! Built without `alloc`. Records are POD-style with `&'static`
//! borrows: the generated source emits `&'static [u8]` /
//! `&'static [AssetId]` slices that the linker pins next to the
//! `include_bytes!` data. Heap-free by construction.

#![no_std]
#![warn(missing_docs)]

/// Fixed-pool runtime traversal over cooked room portals.
pub mod portal_visibility;

/// Stable identifier assigned to every level asset by the editor
/// compiler. `AssetId` values are deterministic across runs:
/// rooms first (in scene-tree order), then textures (ordered by
/// first use in cooked material slot order).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct AssetId(pub u16);

macro_rules! typed_index {
    ($(#[$meta:meta])* pub struct $name:ident;) => {
        $(#[$meta])*
        #[repr(transparent)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub struct $name(pub u16);

        impl $name {
            /// Zero index.
            pub const ZERO: Self = Self(0);

            /// Build from raw manifest storage.
            pub const fn new(raw: u16) -> Self {
                Self(raw)
            }

            /// Return raw manifest storage.
            pub const fn raw(self) -> u16 {
                self.0
            }

            /// Convert to `usize` for slice indexing.
            pub const fn to_usize(self) -> usize {
                self.0 as usize
            }
        }
    };
}

typed_index! {
    /// Index into the generated `ROOMS` table.
    pub struct RoomIndex;
}

typed_index! {
    /// Index into the generated `MATERIALS` table.
    pub struct MaterialIndex;
}

typed_index! {
    /// Index into the generated `VISIBILITY_CELLS` table.
    pub struct VisibilityCellIndex;
}

typed_index! {
    /// Local material slot stored inside a cooked `.psxw` face.
    pub struct MaterialSlot;
}

typed_index! {
    /// Index into the generated `MODELS` table.
    pub struct ModelIndex;
}

typed_index! {
    /// Index into the generated global `MODEL_CLIPS` table.
    pub struct ModelClipTableIndex;
}

typed_index! {
    /// Index into the generated `MODEL_SOCKETS` table.
    pub struct ModelSocketIndex;
}

typed_index! {
    /// Index into the generated `MODEL_FRAME_BOUNDS` table.
    pub struct ModelFrameBoundsIndex;
}

/// Room record flags.
pub mod room_flags {
    /// Per-room fog/depth cue is enabled.
    pub const FOG_ENABLED: u16 = 1 << 0;
    /// Per-room screen-space falling atmosphere is enabled.
    pub const ATMOSPHERE_ENABLED: u16 = 1 << 1;
}

/// Sky record flags.
pub mod sky_flags {
    /// A sky gradient should be drawn before room geometry.
    pub const ENABLED: u16 = 1 << 0;
}

/// Cloud-layer record flags.
pub mod cloud_layer_flags {
    /// Cloud layer should be baked and drawn.
    pub const ENABLED: u16 = 1 << 0;
}

/// Far-vista record flags.
pub mod far_vista_flags {
    /// A far-vista ring should be drawn between sky and room geometry.
    pub const ENABLED: u16 = 1 << 0;
    /// The ring has one or more texture panel assets available.
    pub const TEXTURED: u16 = 1 << 1;
}

/// Equipment record flags.
pub mod equipment_flags {
    /// Equipment belongs to the player controller and should follow
    /// the live player transform/animation instead of the baked
    /// authoring transform.
    pub const PLAYER: u16 = 1 << 0;
}

/// Image prop record flags.
pub mod image_prop_flags {
    /// Prop rotates around Y to face the active camera while staying upright.
    pub const CYLINDRICAL_BILLBOARD: u16 = 1 << 0;
}

/// Face slots on an authored boxed prop.
pub const BOX_PROP_FACE_COUNT: usize = 6;
/// Editable vertex count on an authored boxed prop.
pub const BOX_PROP_VERTEX_COUNT: usize = 8;

/// Box prop record flags.
pub mod box_prop_flags {
    /// Prop emits a static collision blocker for the character motor.
    pub const COLLISION_ENABLED: u16 = 1 << 0;
    /// Prop breaks when the player body overlaps it while walking.
    pub const BREAK_ON_WALK: u16 = 1 << 1;
    /// Prop breaks when the player body overlaps it while running.
    pub const BREAK_ON_RUN: u16 = 1 << 2;
    /// Prop breaks when the player's attack volume overlaps it.
    pub const BREAK_ON_ATTACK: u16 = 1 << 3;
    /// All authored break trigger bits.
    pub const BREAK_ON_MASK: u16 = BREAK_ON_WALK | BREAK_ON_RUN | BREAK_ON_ATTACK;
}

/// Model clip bounds/calibration flags.
pub mod model_clip_flags {
    /// Runtime should cancel root translation for this clip.
    pub const IN_PLACE: u16 = 1 << 0;
}

/// Per-character action playback flags.
pub mod character_action_flags {
    /// The action should loop while the gameplay state remains active.
    pub const LOOPING: u8 = 1 << 0;
    /// The action binding explicitly overrides the clip's baked
    /// in-place calibration.
    pub const IN_PLACE_OVERRIDE: u8 = 1 << 1;
    /// When [`IN_PLACE_OVERRIDE`] is set, cancel root translation
    /// for this action.
    pub const IN_PLACE: u8 = 1 << 2;
}

typed_index! {
    /// Clip index local to one model's clip slice.
    pub struct ModelClipIndex;
}

typed_index! {
    /// Index into the generated `CHARACTERS` table.
    pub struct CharacterIndex;
}

typed_index! {
    /// Index into the generated `WEAPONS` table.
    pub struct WeaponIndex;
}

typed_index! {
    /// Index into the generated `WEAPON_HITBOXES` table.
    pub struct WeaponHitboxIndex;
}

typed_index! {
    /// Runtime resource slot for entity records.
    pub struct ResourceSlot;
}

/// Optional local model-clip index.
///
/// Used for both "no authored clip" character fields and "inherit
/// the model default" model-instance fields. The named constants keep
/// those call sites readable while preserving the compact `u16`
/// manifest representation.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct OptionalModelClipIndex(pub u16);

impl OptionalModelClipIndex {
    /// Sentinel for "no clip authored".
    pub const NONE: Self = Self(u16::MAX);
    /// Sentinel for "inherit the owning model's default clip".
    pub const INHERIT: Self = Self(u16::MAX);

    /// Build an optional value that contains a local clip index.
    pub const fn some(index: ModelClipIndex) -> Self {
        Self(index.raw())
    }

    /// Build directly from raw manifest storage.
    pub const fn from_raw(raw: u16) -> Self {
        Self(raw)
    }

    /// Return raw manifest storage.
    pub const fn raw(self) -> u16 {
        self.0
    }

    /// Return `true` when a real local clip index is present.
    pub const fn is_some(self) -> bool {
        self.0 != u16::MAX
    }

    /// Return `true` when this stores the sentinel value.
    pub const fn is_none(self) -> bool {
        self.0 == u16::MAX
    }

    /// Convert to a local clip index if present.
    pub const fn to_option(self) -> Option<ModelClipIndex> {
        if self.is_some() {
            Some(ModelClipIndex(self.0))
        } else {
            None
        }
    }

    /// Return the contained clip index, or `fallback` for the sentinel.
    pub const fn unwrap_or(self, fallback: ModelClipIndex) -> ModelClipIndex {
        match self.to_option() {
            Some(index) => index,
            None => fallback,
        }
    }
}

/// Coarse asset class -- the runtime branches on this to pick a
/// loader (`World::from_bytes` for rooms, `Texture::from_bytes`
/// for textures). Restricted to the variants generated *and*
/// consumed in this pass; future kinds (`ActorModel`,
/// `LightSet`, `FarfieldCard`, `AudioBank`, …) land when both
/// sides exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AssetKind {
    /// Cooked `.psxw` room blob.
    RoomWorld,
    /// Cooked `.psxt` texture blob (room material atlas, model
    /// atlas, etc -- any cooked indexed-colour PSX texture).
    Texture,
    /// Cooked `.psxmdl` animated/static model blob, bound to a
    /// model atlas asset and any number of clip assets.
    ModelMesh,
    /// Cooked `.psxanim` skeletal animation clip -- references
    /// joint count + frames matching its owning model.
    ModelAnimation,
}

/// One asset in the master table. The byte slice is the live
/// payload -- `include_bytes!` today, a stream-pack offset later.
/// `ram_bytes` and `vram_bytes` are budget hints the residency
/// manager can use to refuse oversize bind sets without parsing
/// the payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelAssetRecord {
    /// Stable id assigned by the compiler.
    pub id: AssetId,
    /// Asset class -- picks the loader.
    pub kind: AssetKind,
    /// Backing payload. For `include_bytes!`-baked assets this
    /// points into the EXE; for future stream packs this will be
    /// the live in-memory slice once the pack is paged in.
    pub bytes: &'static [u8],
    /// RAM cost in bytes. For embedded assets this equals
    /// `bytes.len()`; a stream pack would report the asset's
    /// in-RAM size after decompression.
    pub ram_bytes: u32,
    /// VRAM cost in bytes if this asset uploads to VRAM
    /// (textures). `0` for RAM-only assets (room worlds).
    pub vram_bytes: u32,
    /// Reserved.
    pub flags: u16,
}

/// One cooked cyclorama backdrop quad.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCycloramaQuadRecord {
    /// Unit direction vectors in Q0.12-ish scale, ordered as
    /// top-left, top-right, bottom-left, bottom-right in angular
    /// cyclorama space. Runtime applies camera rotation only.
    pub direction_q12: [[i16; 3]; 4],
    /// Per-corner Gouraud colours.
    pub rgb: [[u8; 3]; 4],
    /// Reserved.
    pub flags: u16,
}

/// Resolved sky settings for one cooked room.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelSkyRecord {
    /// Zenith colour.
    pub top_rgb: [u8; 3],
    /// Colour at the horizon line.
    pub horizon_rgb: [u8; 3],
    /// Colour at the bottom of the frame.
    pub bottom_rgb: [u8; 3],
    /// Horizon line as a percentage of screen height.
    pub horizon_percent: u8,
    /// Angular thickness of the horizon colour band.
    pub horizon_thickness_percent: u8,
    /// Horizontal cyclorama subdivisions.
    pub skybox_columns: u8,
    /// Vertical cyclorama subdivisions.
    pub skybox_rows: u8,
    /// Sky flags.
    pub flags: u16,
    /// Cooked panorama/cyclorama backdrop geometry.
    pub cyclorama_quads: &'static [LevelCycloramaQuadRecord],
    /// Optional authored cloud layer used by the cooked cyclorama.
    pub cloud_layer: LevelCloudLayerRecord,
}

impl LevelSkyRecord {
    /// Default dark gradient used by placeholder manifests.
    pub const DEFAULT: Self = Self {
        top_rgb: [7, 8, 14],
        horizon_rgb: [32, 30, 34],
        bottom_rgb: [5, 7, 12],
        horizon_percent: 58,
        horizon_thickness_percent: 8,
        skybox_columns: 16,
        skybox_rows: 10,
        flags: sky_flags::ENABLED,
        cyclorama_quads: &[],
        cloud_layer: LevelCloudLayerRecord::DEFAULT,
    };
}

/// Resolved cloud-layer settings for one cooked room.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCloudLayerRecord {
    /// Cooked 4bpp multi-CLUT sky panorama texture, or `AssetId(u16::MAX)`.
    pub texture_asset: AssetId,
    /// Cloud highlight colour used by cyclorama cloud streaks.
    pub color_rgb: [u8; 3],
    /// Cloud coverage threshold, 0..=255.
    pub density: u8,
    /// Cyclorama cloud-band vertical bias.
    pub altitude: u16,
    /// Cyclorama cloud-band width.
    pub extent: u16,
    /// Noise/tile repeats across the cloud layer.
    pub tile_count: u8,
    /// Reserved cloud scroll speed.
    pub scroll_speed: [i16; 2],
    /// Cloud-noise seed used by the cooked cyclorama.
    pub noise_seed: u32,
    /// Cloud-layer flags.
    pub flags: u16,
}

impl LevelCloudLayerRecord {
    /// Disabled-by-default placeholder.
    pub const DEFAULT: Self = Self {
        texture_asset: AssetId(u16::MAX),
        color_rgb: [220, 220, 232],
        density: 128,
        altitude: 6_144,
        extent: 24_576,
        tile_count: 4,
        scroll_speed: [4, 0],
        noise_seed: 0x5a7b_c91d,
        flags: 0,
    };
}

/// Resolved distant scenery ring settings for one cooked room.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelFarVistaRecord {
    /// Transparent texture panel assets. Empty means no texture;
    /// one entry repeats around the ring; multiple entries map to
    /// ring segments in order. `AssetId(u16::MAX)` entries draw as
    /// tinted placeholder cards.
    pub texture_assets: &'static [AssetId],
    /// Radius from camera/player in engine units.
    pub radius: i32,
    /// Ring height in engine units.
    pub height: i32,
    /// Bottom-edge offset from camera height in engine units.
    pub vertical_offset: i32,
    /// Number of cards around the cylinder.
    pub segments: u8,
    /// World yaw rotation in degrees.
    pub rotation_degrees: i16,
    /// Tint applied to placeholder and textured cards.
    pub tint_rgb: [u8; 3],
    /// Far-vista flags.
    pub flags: u16,
}

impl LevelFarVistaRecord {
    /// Disabled default used by placeholder manifests.
    pub const DEFAULT: Self = Self {
        texture_assets: &[],
        radius: 18_000,
        height: 4_096,
        vertical_offset: -512,
        segments: 12,
        rotation_degrees: 0,
        tint_rgb: [54, 58, 62],
        flags: 0,
    };
}

/// Resolved third-person camera settings for one cooked room.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCameraRecord {
    /// Preferred trailing distance from focus to camera.
    pub distance: i32,
    /// Camera origin height above the player origin.
    pub height: i32,
    /// Look-at height above the player origin.
    pub target_height: i32,
    /// Minimum camera origin height above the sampled floor.
    pub min_floor_clearance: i32,
}

impl LevelCameraRecord {
    /// Default camera used by placeholder manifests.
    pub const DEFAULT: Self = Self {
        distance: 2_700,
        height: 1_280,
        target_height: 640,
        min_floor_clearance: 64,
    };
}

/// One room. References its world asset by id and points into
/// the global [`LevelMaterialRecord`] table via
/// `material_first` / `material_count`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelRoomRecord {
    /// Display name -- surfaces in editor logs / debug HUDs.
    pub name: &'static str,
    /// Cooked `.psxw` asset.
    pub world_asset: AssetId,
    /// Editor-side origin X (sectors). Diagnostic only -- the
    /// cooker normalizes geometry to be array-rooted.
    pub origin_x: i32,
    /// Editor-side origin Z.
    pub origin_z: i32,
    /// Engine units per sector.
    pub sector_size: i32,
    /// Camera-space far plane used for room/actor rendering.
    pub draw_distance: i32,
    /// Runtime room activation radius in world sectors.
    pub chunk_activation_radius_sectors: i32,
    /// Cooked PVS traversal radius in room cells.
    pub visibility_radius: u16,
    /// Maximum cooked room payloads kept resident for this world.
    pub resident_chunk_limit: u8,
    /// Maximum cooked rooms selected for drawing/collision for this world.
    pub visible_chunk_limit: u8,
    /// First index into the global `MATERIALS` table for this
    /// room's material slice.
    pub material_first: MaterialIndex,
    /// Number of `LevelMaterialRecord`s in this room's slice.
    /// Matches the cooked `.psxw`'s material count.
    pub material_count: u16,
    /// First directed portal in `ROOM_PORTALS` whose source is this room.
    pub portal_first: u16,
    /// Number of directed portal records sourced from this room.
    pub portal_count: u8,
    /// First room index in `ROOM_NEAR_ROOMS`.
    pub near_room_first: u16,
    /// Number of near-room records.
    pub near_room_count: u8,
    /// First room index in `ROOM_OVERLAPPED_ROOMS`.
    pub overlapped_room_first: u16,
    /// Number of overlapped-room records.
    pub overlapped_room_count: u8,
    /// Fog/depth-cue far colour.
    pub fog_rgb: [u8; 3],
    /// Fog start distance in engine units.
    pub fog_near: i32,
    /// Fog end distance in engine units.
    pub fog_far: i32,
    /// Base colour for the cheap screen-space room atmosphere pass.
    pub atmosphere_rgb: [u8; 3],
    /// Number of screen-space particles to draw for this room.
    pub atmosphere_density: u8,
    /// Base vertical particle speed, in 1/16 pixel-per-vblank units.
    pub atmosphere_fall_speed_q4: i16,
    /// Base horizontal particle speed, in 1/16 pixel-per-vblank units.
    pub atmosphere_wind_speed_q4: i16,
    /// Resolved world sky for this room.
    pub sky: LevelSkyRecord,
    /// Resolved distant scenery ring for this room.
    pub far_vista: LevelFarVistaRecord,
    /// Resolved third-person camera for this room.
    pub camera: LevelCameraRecord,
    /// Reserved.
    pub flags: u16,
}

/// One directed portal between two cooked runtime rooms.
///
/// `normal_*` points back toward `source_room`, away from
/// `destination_room`, and the vertex arrays encode the portal
/// rectangle as `[BL, BR, TR, TL]` in world-space engine units.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelRoomPortalRecord {
    /// Source room in the generated `ROOMS` table.
    pub source_room: RoomIndex,
    /// Destination room in the generated `ROOMS` table.
    pub destination_room: RoomIndex,
    /// Portal kind: `0` wall, `1` vertical placeholder.
    pub kind: u8,
    /// Source-facing normal X.
    pub normal_x: i16,
    /// Source-facing normal Y.
    pub normal_y: i16,
    /// Source-facing normal Z.
    pub normal_z: i16,
    /// X coordinate for each portal vertex.
    pub vertex_x: [i32; 4],
    /// Y coordinate for each portal vertex.
    pub vertex_y: [i32; 4],
    /// Z coordinate for each portal vertex.
    pub vertex_z: [i32; 4],
}

/// Cardinal open-portal neighbours for one cooked room.
///
/// Missing neighbours are encoded as `RoomIndex(u16::MAX)` so the
/// record stays plain data in generated manifests.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelChunkNeighbours {
    /// Room reachable through the north edge, if any.
    pub north: RoomIndex,
    /// Room reachable through the east edge, if any.
    pub east: RoomIndex,
    /// Room reachable through the south edge, if any.
    pub south: RoomIndex,
    /// Room reachable through the west edge, if any.
    pub west: RoomIndex,
}

impl LevelChunkNeighbours {
    /// Sentinel used for absent neighbour links.
    pub const NONE: RoomIndex = RoomIndex(u16::MAX);

    /// Empty neighbour set.
    pub const EMPTY: Self = Self {
        north: Self::NONE,
        east: Self::NONE,
        south: Self::NONE,
        west: Self::NONE,
    };
}

/// Runtime room metadata emitted by the playtest cooker.
///
/// Authored editor Rooms may be contiguous worlds; the cooker derives
/// manual portal-delimited runtime rooms from them. This table lets
/// the engine stream and render by explicit portal connectivity instead
/// of deriving active neighbours from broad room bounds.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelChunkRecord {
    /// Owning room/chunk index in the generated `ROOMS` table.
    pub room: RoomIndex,
    /// Stable authored Room node id, truncated to 32 bits for a
    /// compact runtime diagnostic key.
    pub authored_room: u32,
    /// Stable runtime-room order inside the authored Room's cook plan.
    pub chunk_index: u16,
    /// Runtime room origin X in authored grid sectors.
    pub origin_x: i32,
    /// Runtime room origin Z in authored grid sectors.
    pub origin_z: i32,
    /// Runtime room width in sectors.
    pub width: u16,
    /// Runtime room depth in sectors.
    pub depth: u16,
    /// Cardinal portal links inside the same authored Room.
    pub neighbours: LevelChunkNeighbours,
    /// Reserved.
    pub flags: u16,
}

/// Generated CD streaming table entry for one cooked room payload.
///
/// The cooker emits this table from the same sector layout used to
/// build `WORLD.PAK`, so runtime room streaming can seek directly to
/// a room payload without reading the pack header/table from disc.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelWorldPackEntryRecord {
    /// Room/chunk id in the generated `ROOMS` table.
    pub room: RoomIndex,
    /// Payload start sector relative to the beginning of `WORLD.PAK`.
    pub sector_offset: u32,
    /// Sector-aligned payload length.
    pub sector_count: u32,
    /// Original unpadded byte size.
    pub byte_size: u32,
    /// FNV-1a checksum of the unpadded payload.
    pub checksum: u32,
}

/// Magic at the start of a streamed room chunk payload.
///
/// A streamed chunk stores a collision payload plus renderer-native
/// cache records. The fixed header lets the runtime recover both
/// views directly from the CD-loaded slot without rebuilding geometry
/// or carrying a second global cache copy.
pub const STREAMED_ROOM_CHUNK_MAGIC: [u8; 8] = *b"PSXCHNK\0";

/// Streamed room chunk header version with explicit render,
/// per-cell vertex-list, and collision payload boundaries.
pub const STREAMED_ROOM_CHUNK_VERSION: u32 = 3;

/// Byte length of the streamed room chunk header.
pub const STREAMED_ROOM_CHUNK_HEADER_BYTES: usize = 64;

/// Header offsets for a streamed room chunk payload.
///
/// The render path consumes the cache table ranges directly; the
/// collision path consumes `COLLISION_OFFSET/COLLISION_BYTES`.
pub mod streamed_room_chunk_header {
    /// Header format version.
    pub const VERSION: usize = 8;
    /// Cooked room/chunk id.
    pub const ROOM: usize = 12;
    /// Unpadded payload byte count.
    pub const TOTAL_BYTES: usize = 16;
    /// Offset of the collision payload.
    pub const COLLISION_OFFSET: usize = 20;
    /// Collision payload byte count.
    pub const COLLISION_BYTES: usize = 24;
    /// Offset of the cached room-cell table.
    pub const CELLS_OFFSET: usize = 28;
    /// Number of cached room-cell records.
    pub const CELL_COUNT: usize = 32;
    /// Offset of the cached vertex table.
    pub const VERTICES_OFFSET: usize = 36;
    /// Number of cached vertex records.
    pub const VERTEX_COUNT: usize = 40;
    /// Offset of the cached surface table.
    pub const SURFACES_OFFSET: usize = 44;
    /// Number of cached surface records.
    pub const SURFACE_COUNT: usize = 48;
    /// Offset of the per-cell cached vertex-index table.
    pub const CELL_VERTICES_OFFSET: usize = 52;
    /// Number of per-cell cached vertex indices.
    pub const CELL_VERTEX_COUNT: usize = 56;
    /// Payload format flags.
    pub const FLAGS: usize = 60;
}

/// The collision payload is the compact collision-only room format.
pub const STREAMED_ROOM_CHUNK_FLAG_COLLISION_COMPACT: u32 = 1 << 0;

/// Magic at the start of a compact collision-only room payload.
pub const COMPACT_COLLISION_MAGIC: [u8; 8] = *b"PSXCOLL\0";

/// Version of the compact collision-only room payload.
pub const COMPACT_COLLISION_VERSION: u32 = 2;

/// Byte length of the compact collision header.
pub const COMPACT_COLLISION_HEADER_BYTES: usize = 36;

/// Byte length of one compact collision sector record.
pub const COMPACT_COLLISION_SECTOR_BYTES: usize = 48;

/// Sentinel stored in compact collision sector floor links when no room exists.
pub const COMPACT_COLLISION_NO_ROOM: u16 = u16::MAX;

/// Byte length of one compact collision wall record.
pub const COMPACT_COLLISION_WALL_BYTES: usize = 20;

/// Byte length of one compact collision height-override record.
pub const COMPACT_COLLISION_HEIGHT_OVERRIDE_BYTES: usize = 28;

/// Header offsets for a compact collision-only payload.
pub mod compact_collision_header {
    /// Header format version.
    pub const VERSION: usize = 8;
    /// Width in sectors.
    pub const WIDTH: usize = 12;
    /// Depth in sectors.
    pub const DEPTH: usize = 14;
    /// Engine units per sector.
    pub const SECTOR_SIZE: usize = 16;
    /// Number of sector records.
    pub const SECTOR_COUNT: usize = 20;
    /// Number of wall records.
    pub const WALL_COUNT: usize = 22;
    /// Number of height-override records.
    pub const HEIGHT_OVERRIDE_COUNT: usize = 24;
    /// Reserved header word.
    pub const RESERVED: usize = 26;
    /// Ambient room RGB used by actor lighting.
    pub const AMBIENT_RGB: usize = 28;
    /// Payload flags.
    pub const FLAGS: usize = 32;
}

/// Flags stored in compact collision sector records.
pub mod compact_collision_sector_flags {
    /// Sector has a floor surface.
    pub const HAS_FLOOR: u8 = 1 << 0;
    /// Sector has a ceiling surface.
    pub const HAS_CEILING: u8 = 1 << 1;
    /// Floor has at least one walkable triangle.
    pub const FLOOR_WALKABLE: u8 = 1 << 2;
    /// Ceiling has at least one walkable triangle.
    pub const CEILING_WALKABLE: u8 = 1 << 3;
    /// Sector can move upward into another runtime room.
    pub const HAS_FLOOR_ABOVE: u8 = 1 << 4;
    /// Sector can move downward into another runtime room.
    pub const HAS_FLOOR_BELOW: u8 = 1 << 5;
}

/// Triangle bits stored in compact collision sector records.
pub mod compact_collision_triangle_flags {
    /// Triangle A is present.
    pub const TRI_A_PRESENT: u8 = 1 << 0;
    /// Triangle B is present.
    pub const TRI_B_PRESENT: u8 = 1 << 1;
    /// Triangle A is walkable.
    pub const TRI_A_WALKABLE: u8 = 1 << 2;
    /// Triangle B is walkable.
    pub const TRI_B_WALKABLE: u8 = 1 << 3;
}

/// Surface ids stored in compact collision height overrides.
pub mod compact_collision_surface {
    /// Sector floor.
    pub const FLOOR: u8 = 0;
    /// Sector ceiling.
    pub const CEILING: u8 = 1;
}

/// Flags stored in compact collision wall records.
pub mod compact_collision_wall_flags {
    /// Wall blocks collision.
    pub const SOLID: u8 = 1 << 0;
}

/// Visibility metadata for one cooked room/chunk. Points into the
/// generated compact cell table and the cooked position-cell PVS table.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelRoomVisibilityRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// First cell record for this room.
    pub cell_first: VisibilityCellIndex,
    /// Number of cell records in this room's visibility slice.
    pub cell_count: u16,
    /// First PVS record for this room in `VISIBILITY_PVS`.
    pub pvs_first: u32,
    /// Number of PVS records for this room. This normally matches
    /// `cell_count`; each visibility cell has one anchor PVS.
    pub pvs_count: u16,
    /// Reserved.
    pub flags: u16,
}

/// One cooked position-cell PVS bitset slice.
///
/// Bits index the owning room's `LevelVisibilityCellRecord` slice.
/// The runtime still applies camera/global filters and depth sorting,
/// but it no longer builds a lookup table or traverses portals while
/// rendering.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelVisibilityPvsRecord {
    /// First byte in `VISIBILITY_PVS_BITS`.
    pub byte_first: u32,
    /// Number of bitset bytes.
    pub byte_count: u16,
    /// Reserved.
    pub flags: u16,
}

/// Edge bitmasks used by [`LevelVisibilityCellRecord::portal_mask`]
/// and [`LevelVisibilityCellRecord::blocker_mask`].
pub mod visibility_edge_flags {
    /// North edge, negative Z.
    pub const NORTH: u8 = 1 << 0;
    /// East edge, positive X.
    pub const EAST: u8 = 1 << 1;
    /// South edge, positive Z.
    pub const SOUTH: u8 = 1 << 2;
    /// West edge, negative X.
    pub const WEST: u8 = 1 << 3;
}

/// Per-cell visibility flags.
pub mod visibility_cell_flags {
    /// Cell contains renderable room geometry.
    pub const HAS_GEOMETRY: u16 = 1 << 0;
}

/// One generated grid cell with precomputed bounds and portal/blocker
/// metadata. Bounds are room-local engine units and are used by the
/// runtime to avoid walking wall/floor records just to frustum-test a
/// cell.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelVisibilityCellRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Grid X coordinate inside the cooked `.psxw`.
    pub x: u16,
    /// Grid Z coordinate inside the cooked `.psxw`.
    pub z: u16,
    /// Minimum authored surface height in this cell.
    pub min_y: i32,
    /// Maximum authored surface height in this cell.
    pub max_y: i32,
    /// Cardinal edges that are considered open for conservative
    /// portal-style visibility traversal.
    pub portal_mask: u8,
    /// Cardinal edges that contain a conservative full-height solid
    /// blocker.
    pub blocker_mask: u8,
    /// Room-local index into the matching `ROOM_CACHE_CELLS` slice,
    /// or `u16::MAX` when no generated render-cache cell exists.
    pub cache_cell_index: u16,
    /// Reserved.
    pub flags: u16,
}

/// Per-room slice into generated cached room-surface records.
///
/// The cache payload is frame-invariant room geometry: populated
/// cells, deduplicated room-local vertices, and predecoded surface
/// records. Camera projection remains runtime scratch.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelRoomSurfaceCacheRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// First cell record for this room in `ROOM_CACHE_CELLS`.
    pub cell_first: u32,
    /// Number of cached cell records for this room.
    pub cell_count: u16,
    /// First per-cell vertex index for this room in
    /// `ROOM_CACHE_CELL_VERTICES`. A zero count means the runtime
    /// derives the visible vertex set from cell surface ranges.
    pub cell_vertex_first: u32,
    /// Number of per-cell vertex indices for this room.
    pub cell_vertex_count: u16,
    /// First vertex record for this room in `ROOM_CACHE_VERTICES`.
    pub vertex_first: u32,
    /// Number of cached vertex records for this room.
    pub vertex_count: u16,
    /// First surface record for this room in `ROOM_CACHE_SURFACES`.
    pub surface_first: u32,
    /// Number of cached surface records for this room.
    pub surface_count: u16,
    /// Reserved.
    pub flags: u16,
}

/// Generated cached room cell header.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCachedRoomCellRecord {
    /// Grid X coordinate inside the cooked room.
    pub x: u16,
    /// Grid Z coordinate inside the cooked room.
    pub z: u16,
    /// Minimum authored surface height in room-local engine units.
    pub min_y: i32,
    /// Maximum authored surface height in room-local engine units.
    pub max_y: i32,
    /// Precomputed visibility center as `[x, y, z]`.
    pub visibility_center: [i32; 3],
    /// Precomputed visibility radius.
    pub visibility_radius: i32,
    /// First cached surface in this cell's room-local surface slice.
    pub surface_first: u16,
    /// Number of cached surfaces in this cell.
    pub surface_count: u16,
    /// First cached vertex index in this cell's room-local
    /// cell-vertex slice.
    pub vertex_first: u16,
    /// Number of unique cached vertices referenced by this cell.
    pub vertex_count: u16,
}

/// Generated cached room vertex.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCachedRoomVertexRecord {
    /// Room-local X coordinate in engine units.
    pub x: i32,
    /// Room-local Y coordinate in engine units.
    pub y: i32,
    /// Room-local Z coordinate in engine units.
    pub z: i32,
}

/// Generated cached room surface.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCachedRoomSurfaceRecord {
    /// Local room material slot referenced by this surface.
    pub material_slot: u16,
    /// Indices into the room-local cached vertex stream.
    pub vertex_indices: [u16; 4],
    /// Sector X coordinate for the reconstructed lighting sample.
    pub sample_sx: u16,
    /// Sector Z coordinate for the reconstructed lighting sample.
    pub sample_sz: u16,
    /// Surface ordinal for the reconstructed lighting sample.
    pub sample_ordinal: u16,
    /// Packed low 16 bits of each packet UV word: `u | v << 8`.
    pub uv_words: [u16; 4],
    /// Cached baked RGB values.
    pub baked_vertex_rgb: [(u8, u8, u8); 4],
    /// Packed surface kind plus baked-light flag.
    pub kind_flags: u8,
    /// Runtime wall direction when this is a wall surface.
    pub wall_direction: u8,
    /// Authored diagonal split id for floors/ceilings.
    pub split: u8,
    /// Split-triangle index, or the whole-quad sentinel.
    pub triangle_index: u8,
}

/// One material slot for one room. The compiler emits records
/// in `(room, local_slot)` order; the runtime walks the room's
/// slice and binds `local_slot` → `texture_asset` into a
/// `TextureMaterial` table indexed by the cooked face's stored
/// material slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelMaterialRecord {
    /// Owning room index in [`LevelRoomRecord`] order.
    pub room: RoomIndex,
    /// Cooked-world local material slot. Matches the value the
    /// `.psxw` stores per-face / per-wall.
    pub local_slot: MaterialSlot,
    /// Texture asset bound at this slot.
    pub texture_asset: AssetId,
    /// Per-material modulation tint. Renderer multiplies the
    /// texture sample by this colour.
    pub tint_rgb: [u8; 3],
    /// Runtime material flags. Low two bits encode face sidedness
    /// using [`material_flags::FACE_*`].
    pub flags: u16,
}

/// Material flag bits stored in [`LevelMaterialRecord::flags`].
pub mod material_flags {
    /// Mask for the face-sidedness bits.
    pub const FACE_MASK: u16 = 0x0003;
    /// Draw only the authored front side.
    pub const FACE_FRONT: u16 = 0x0000;
    /// Draw only the opposite side.
    pub const FACE_BACK: u16 = 0x0001;
    /// Draw either winding.
    pub const FACE_BOTH: u16 = 0x0002;
}

/// Which side of a room face should render.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LevelMaterialSidedness {
    /// Authored/front winding only.
    Front,
    /// Opposite winding only.
    Back,
    /// No winding cull.
    Both,
}

impl LevelMaterialRecord {
    /// Decode the material's face-sidedness flags.
    pub const fn sidedness(self) -> LevelMaterialSidedness {
        match self.flags & material_flags::FACE_MASK {
            material_flags::FACE_BACK => LevelMaterialSidedness::Back,
            material_flags::FACE_BOTH => LevelMaterialSidedness::Both,
            _ => LevelMaterialSidedness::Front,
        }
    }
}

/// Per-room residency contract. The runtime calls
/// `ResidencyManager::ensure_room_resident` with this record on
/// room enter; it lists exactly the assets that must be in RAM
/// and VRAM before the room can render.
///
/// `warm_*` lists are placeholders for future preload hints
/// (neighbour rooms, soon-to-be-streamed assets). They're
/// always empty in this pass.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RoomResidencyRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Assets that must be RAM-resident before render.
    pub required_ram: &'static [AssetId],
    /// Assets that must be VRAM-resident (uploaded textures).
    pub required_vram: &'static [AssetId],
    /// Preload-hint assets that *should* be RAM-resident soon
    /// (e.g. neighbour rooms across an open portal). Empty in
    /// this pass.
    pub warm_ram: &'static [AssetId],
    /// Same idea for VRAM. Empty in this pass.
    pub warm_vram: &'static [AssetId],
}

/// Player spawn point. Coordinates are room-local engine units
/// (the same space the cooked `.psxw` lives in -- array-rooted
/// at world `(0, 0)`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlayerSpawnRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Room-local X.
    pub x: i32,
    /// Y (typically 0 for floor-anchored spawns).
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Yaw in PSX angle units (`0..4096`).
    pub yaw: i16,
    /// Reserved. Bit 0 = "spawn enabled" by current writer.
    pub flags: u16,
}

/// Coarse runtime kind for [`EntityRecord`]. Markers are
/// visual debug stubs (cubes); `StaticMesh` will reference a
/// resource slot once the asset pipeline supports meshes as
/// `LevelAssetRecord`s.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntityKind {
    /// Visual marker (debug cube).
    Marker,
    /// Static mesh instance pinned by `resource_slot`.
    StaticMesh,
}

/// One non-spawn entity. Same room-local coordinate convention
/// as [`PlayerSpawnRecord`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EntityRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Entity kind.
    pub kind: EntityKind,
    /// Room-local X.
    pub x: i32,
    /// Y.
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Yaw, PSX angle units.
    pub yaw: i16,
    /// Resource slot (0 if unused -- e.g. for `Marker`).
    pub resource_slot: ResourceSlot,
    /// Reserved.
    pub flags: u16,
}

/// One animation clip bound to a [`LevelModelRecord`]. The clip
/// asset's joint count is checked against the owning model's
/// joint count at cook time; runtime trusts the contract.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelClipRecord {
    /// Owning model index in [`LevelModelRecord`] order.
    pub model: ModelIndex,
    /// Display name -- surfaces in editor logs / debug HUDs.
    pub name: &'static str,
    /// Cooked `.psxanim` asset.
    pub animation_asset: AssetId,
}

/// Bounds metadata for one global model-clip entry.
///
/// The generated table is emitted in the same order as
/// `MODEL_CLIPS`, so runtime code can index it by
/// [`ModelClipTableIndex`] and avoid walking broad asset tables
/// during the frame path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelClipBoundsRecord {
    /// Owning model.
    pub model: ModelIndex,
    /// Global clip table entry these frame bounds describe.
    pub clip: ModelClipTableIndex,
    /// First frame-bound record for this clip.
    pub first_frame: ModelFrameBoundsIndex,
    /// Number of frame-bound records.
    pub frame_count: u16,
    /// Grounding floor in raw model-local units.
    pub floor_y: i32,
    /// Additional model-local pose offset in cooked pose units.
    pub pose_offset: [i32; 3],
    /// See [`model_clip_flags`].
    pub flags: u16,
}

/// Conservative local-space sphere for one sampled animation frame.
///
/// `center` is relative to the model origin after model-local
/// animation and model-local-to-world scale have been applied, but
/// before instance yaw and world translation. `radius` is in engine
/// world units and intentionally conservative so culling never clips
/// a visible animated limb.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelFrameBoundsRecord {
    /// Model-local center in engine world units.
    pub center: [i32; 3],
    /// Conservative sphere radius in engine world units.
    pub radius: i32,
}

/// One cooked PSX model: `.psxmdl` mesh, optional `.psxt`
/// atlas, and a slice of clips. Instances reference this record
/// by index via [`LevelModelInstanceRecord::model`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelRecord {
    /// Display name.
    pub name: &'static str,
    /// Cooked `.psxmdl` asset.
    pub mesh_asset: AssetId,
    /// Atlas texture asset. The schema keeps this `Option` for
    /// future flat-shaded / untextured model paths, but the
    /// playtest cooker rejects placed instances of any model
    /// without an atlas -- the runtime model path renders
    /// textured animated models only.
    pub texture_asset: Option<AssetId>,
    /// First index into the global `MODEL_CLIPS` table.
    pub clip_first: ModelClipTableIndex,
    /// Number of clips in this model's slice.
    pub clip_count: u16,
    /// Default clip index *within this model's slice* -- runtime
    /// instances with no per-instance override pick this clip.
    /// Cooker validation guarantees this resolves to a valid
    /// clip; the runtime never has to fall back to bind pose
    /// (no bind-pose path exists in this pass).
    pub default_clip: ModelClipIndex,
    /// First index into the generated `MODEL_SOCKETS` table.
    pub socket_first: ModelSocketIndex,
    /// Number of sockets in this model's slice.
    pub socket_count: u16,
    /// Suggested world-space height (engine units) -- mirrors
    /// the `.psxmdl` header's `local_to_world` hint.
    pub world_height: u16,
    /// Coarse actor collision radius (engine units). Runtime
    /// gameplay treats placed models as vertical cylinders.
    pub collision_radius: u16,
    /// Reserved.
    pub flags: u16,
}

/// One named attachment socket authored on a model resource.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelSocketRecord {
    /// Owning model index.
    pub model: ModelIndex,
    /// Display/runtime lookup name.
    pub name: &'static str,
    /// Joint index in the cooked model skeleton.
    pub joint: u16,
    /// Local translation relative to that joint pose.
    pub translation: [i32; 3],
    /// Local Euler rotation in Q12 turn units, X/Y/Z.
    pub rotation_q12: [i16; 3],
    /// Reserved.
    pub flags: u16,
}

/// One placed model instance. Coordinates are room-local
/// engine units. `clip` is an index into the owning model's
/// clip slice; `0xFFFF` means "use the model's `default_clip`".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelModelInstanceRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Model index in [`LevelModelRecord`] order.
    pub model: ModelIndex,
    /// Per-instance clip override, or `0xFFFF` to inherit the
    /// model's `default_clip`.
    pub clip: OptionalModelClipIndex,
    /// Room-local X.
    pub x: i32,
    /// Y.
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Yaw, PSX angle units.
    pub yaw: i16,
    /// Render-only yaw from the Model Renderer component, PSX angle units.
    pub visual_yaw: i16,
    /// Render-only model offset from the authored floor anchor,
    /// in entity-local engine units.
    pub visual_offset: [i16; 3],
    /// Render-only uniform scale in Q8 fixed point (`256 = 1.0`).
    pub visual_scale_q8: u16,
    /// Reserved.
    pub flags: u16,
}

/// Sentinel for [`LevelModelInstanceRecord::clip`] meaning
/// "inherit model default".
pub const MODEL_CLIP_INHERIT: OptionalModelClipIndex = OptionalModelClipIndex::INHERIT;

/// One placed flat image prop. Coordinates are room-local engine
/// units and `x/y/z` names the bottom-center anchor of the quad.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelImagePropRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Texture asset used by the prop material.
    pub texture_asset: AssetId,
    /// Bottom-center room-local X.
    pub x: i32,
    /// Bottom Y.
    pub y: i32,
    /// Bottom-center room-local Z.
    pub z: i32,
    /// Static pitch in PSX angle units. Ignored when
    /// [`image_prop_flags::CYLINDRICAL_BILLBOARD`] is set.
    pub pitch: i16,
    /// Static yaw in PSX angle units. Ignored when
    /// [`image_prop_flags::CYLINDRICAL_BILLBOARD`] is set.
    pub yaw: i16,
    /// Static roll in PSX angle units. Ignored when
    /// [`image_prop_flags::CYLINDRICAL_BILLBOARD`] is set.
    pub roll: i16,
    /// Quad width in engine units.
    pub width: u16,
    /// Quad height in engine units.
    pub height: u16,
    /// Per-material modulation tint.
    pub tint_rgb: [u8; 3],
    /// Baked static light base per quad vertex, in perimeter order.
    pub baked_vertex_rgb: [(u8, u8, u8); 4],
    /// Runtime flags.
    pub flags: u16,
}

/// One placed editable box prop. Coordinates are room-local engine
/// units and `x/y/z` names the bottom-center anchor. Vertices are
/// local to that anchor, in bottom-ring then top-ring order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelBoxPropRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Per-face texture asset. `None` means the face is not drawn.
    pub texture_assets: [Option<AssetId>; BOX_PROP_FACE_COUNT],
    /// Bottom-center room-local X.
    pub x: i32,
    /// Bottom Y.
    pub y: i32,
    /// Bottom-center room-local Z.
    pub z: i32,
    /// Static pitch in PSX angle units.
    pub pitch: i16,
    /// Static yaw in PSX angle units.
    pub yaw: i16,
    /// Static roll in PSX angle units.
    pub roll: i16,
    /// Editable local vertices, bottom ring then top ring.
    pub vertices: [[i16; 3]; BOX_PROP_VERTEX_COUNT],
    /// Per-face modulation tint.
    pub tint_rgb: [[u8; 3]; BOX_PROP_FACE_COUNT],
    /// Baked static light base per face vertex.
    pub baked_vertex_rgb: [[(u8, u8, u8); 4]; BOX_PROP_FACE_COUNT],
    /// Runtime flags.
    pub flags: u16,
}

/// Cooked weapon-local hit shape.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WeaponHitShapeRecord {
    /// Box hit volume local to the weapon grip.
    Box {
        /// Local center.
        center: [i32; 3],
        /// Half extents.
        half_extents: [u16; 3],
    },
    /// Capsule hit volume local to the weapon grip.
    Capsule {
        /// Local start.
        start: [i32; 3],
        /// Local end.
        end: [i32; 3],
        /// Radius.
        radius: u16,
    },
}

/// One weapon hitbox and its active animation-frame window.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WeaponHitboxRecord {
    /// Display name.
    pub name: &'static str,
    /// Local shape.
    pub shape: WeaponHitShapeRecord,
    /// First active frame.
    pub active_start_frame: u16,
    /// Last active frame.
    pub active_end_frame: u16,
    /// Reserved.
    pub flags: u16,
}

/// Cooked weapon resource: optional visual model plus grip and
/// hitbox slice. The visual model is optional so designers can
/// author combat volumes before art exists.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelWeaponRecord {
    /// Display name.
    pub name: &'static str,
    /// Optional visual model.
    pub model: Option<ModelIndex>,
    /// Character socket this weapon expects by default.
    pub default_character_socket: &'static str,
    /// Weapon-local grip/pivot name.
    pub grip_name: &'static str,
    /// Weapon-local grip translation.
    pub grip_translation: [i32; 3],
    /// Weapon-local grip rotation, Q12 turns.
    pub grip_rotation_q12: [i16; 3],
    /// First hitbox in `WEAPON_HITBOXES`.
    pub hitbox_first: WeaponHitboxIndex,
    /// Number of hitboxes.
    pub hitbox_count: u16,
    /// Reserved.
    pub flags: u16,
}

/// One Equipment component cooked from an Entity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EquipmentRecord {
    /// Owning room.
    pub room: RoomIndex,
    /// Weapon resource.
    pub weapon: WeaponIndex,
    /// Parent entity room-local X.
    pub x: i32,
    /// Parent entity room-local Y.
    pub y: i32,
    /// Parent entity room-local Z.
    pub z: i32,
    /// Parent entity yaw.
    pub yaw: i16,
    /// Character socket to follow.
    pub character_socket: &'static str,
    /// Weapon grip/pivot to align.
    pub weapon_grip: &'static str,
    /// Reserved.
    pub flags: u16,
}

/// One placed point light. Coordinates are room-local engine
/// units (same convention as model instances and player spawn).
/// Static room geometry is pre-baked into the `.psxw` room blob;
/// dynamic/model lighting can still sample these point-light
/// records at runtime.
///
/// `intensity_q8` is the multiplier in Q8.8 fixed-point
/// (256 = 1.0, 512 = 2.0, ...); the cooker derives it from
/// the editor's `f32` intensity field so the host UI keeps
/// floats while the wire format stays integer-only. `radius`
/// is engine units; surfaces past the radius receive zero
/// contribution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PointLightRecord {
    /// Owning room index.
    pub room: RoomIndex,
    /// Room-local X.
    pub x: i32,
    /// Y.
    pub y: i32,
    /// Room-local Z.
    pub z: i32,
    /// Cutoff distance in engine units. Surfaces beyond this
    /// receive zero contribution. Cooker rejects `0`.
    pub radius: u16,
    /// Brightness multiplier, Q8.8. `256` = 1.0.
    pub intensity_q8: u16,
    /// 8-bit RGB tint applied before the per-surface
    /// attenuation weight.
    pub color: [u8; 3],
    /// Reserved.
    pub flags: u16,
}

/// Sentinel for optional [`LevelCharacterRecord`] clip slots
/// (`run_clip` / `turn_clip`). The runtime treats this as
/// "no clip authored for this role" and falls back to walk /
/// idle as appropriate.
pub const CHARACTER_CLIP_NONE: OptionalModelClipIndex = OptionalModelClipIndex::NONE;

/// Fixed action slots used by [`LevelCharacterRecord::action_clips`].
pub const CHARACTER_ANIMATION_ACTION_COUNT: usize = 12;

/// Runtime animation action slot.
///
/// The editor is free to bind any compatible clip to any slot. The
/// runtime only relies on stable numeric indices so cooked
/// characters stay compact and heap-free.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CharacterAnimationAction {
    /// Standing still.
    Idle = 0,
    /// Normal locomotion.
    Walk = 1,
    /// Fast locomotion.
    Run = 2,
    /// In-place turn, when authored.
    Turn = 3,
    /// Forward evade.
    Roll = 4,
    /// Backward evade.
    Backstep = 5,
    /// Primary attack.
    LightAttack = 6,
    /// Secondary attack.
    HeavyAttack = 7,
    /// Follow-up / combo attack.
    ComboAttack = 8,
    /// Guard / block pose.
    Block = 9,
    /// Damage reaction.
    HitReact = 10,
    /// Death / collapse.
    Death = 11,
}

impl CharacterAnimationAction {
    /// Ordered list matching [`CHARACTER_ANIMATION_ACTION_COUNT`].
    pub const ALL: [Self; CHARACTER_ANIMATION_ACTION_COUNT] = [
        Self::Idle,
        Self::Walk,
        Self::Run,
        Self::Turn,
        Self::Roll,
        Self::Backstep,
        Self::LightAttack,
        Self::HeavyAttack,
        Self::ComboAttack,
        Self::Block,
        Self::HitReact,
        Self::Death,
    ];

    /// Convert to the cooked action slot index.
    pub const fn to_index(self) -> usize {
        self as usize
    }
}

/// Gameplay character -- backing model + role-clip mapping +
/// capsule / camera / controller defaults. Layered on top of
/// a [`LevelModelRecord`]; the player spawn references one of
/// these via [`PlayerControllerRecord::character`] to resolve
/// what to render and how the controller behaves.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LevelCharacterRecord {
    /// Index into [`LevelModelRecord`] this character renders
    /// as. The cooker guarantees this resolves; runtime trusts
    /// the contract.
    pub model: ModelIndex,
    /// Optional clip per [`CharacterAnimationAction`] slot.
    /// Required slots are validated by the cooker; optional slots
    /// use [`CHARACTER_CLIP_NONE`] and runtime fallbacks.
    pub action_clips: [OptionalModelClipIndex; CHARACTER_ANIMATION_ACTION_COUNT],
    /// Per-action playback flags matching [`Self::action_clips`].
    pub action_flags: [u8; CHARACTER_ANIMATION_ACTION_COUNT],
    /// Render-only model offset from the controller root, in
    /// entity-local engine units.
    pub visual_offset: [i16; 3],
    /// Render-only yaw from the Model Renderer component, PSX angle units.
    pub visual_yaw: i16,
    /// Render-only uniform scale in Q8 fixed point (`256 = 1.0`).
    pub visual_scale_q8: u16,
    /// Capsule radius in engine units. Used by collision +
    /// any future debug draw.
    pub radius: u16,
    /// Capsule height in engine units.
    pub height: u16,
    /// Forward walk speed (engine units per 60 Hz frame).
    pub walk_speed: i32,
    /// Forward run speed (engine units per 60 Hz frame).
    pub run_speed: i32,
    /// Yaw rate the controller applies when turning.
    pub turn_speed_degrees_per_second: u16,
    /// Maximum stamina, in Q12-style arbitrary units.
    pub stamina_max_q12: i32,
    /// Minimum stamina required to start sprinting.
    pub sprint_min_q12: i32,
    /// Stamina spent per sprinting display frame.
    pub sprint_drain_q12: i32,
    /// Stamina recovered per grounded non-sprint display frame.
    pub stamina_recover_q12: i32,
    /// Stamina spent to start a roll.
    pub roll_cost_q12: i32,
    /// Roll travel speed in world units per display frame.
    pub roll_speed: i32,
    /// Display frames where roll keeps moving.
    pub roll_active_frames: u8,
    /// Recovery display frames after roll movement ends.
    pub roll_recovery_frames: u8,
    /// Roll invulnerability display frames from action start.
    pub roll_invulnerable_frames: u8,
    /// Stamina spent to start a backstep.
    pub backstep_cost_q12: i32,
    /// Backstep travel speed in world units per display frame.
    pub backstep_speed: i32,
    /// Display frames where backstep keeps moving.
    pub backstep_active_frames: u8,
    /// Recovery display frames after backstep movement ends.
    pub backstep_recovery_frames: u8,
    /// Backstep invulnerability display frames from action start.
    pub backstep_invulnerable_frames: u8,
    /// Distance the third-person camera trails the character.
    pub camera_distance: i32,
    /// Camera vertical offset above the character origin.
    pub camera_height: i32,
    /// Vertical offset of the camera's look-at target above
    /// the character origin.
    pub camera_target_height: i32,
    /// Reserved.
    pub flags: u16,
}

/// Player-controller record: which spawn the player starts at
/// and which character drives them. Generated as a single
/// optional record in the manifest -- `Some` when a player
/// spawn was authored, `None` for headless / preview manifests.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlayerControllerRecord {
    /// Resolved spawn -- same struct the manifest already emits
    /// as a top-level `PLAYER_SPAWN`. Embedded here so the
    /// runtime can look at one record to bring up the player.
    pub spawn: PlayerSpawnRecord,
    /// Index into [`LevelCharacterRecord`] driving the player.
    pub character: CharacterIndex,
    /// Reserved.
    pub flags: u16,
}

/// Linear scan over the master asset table. `O(n)` is fine for
/// the asset counts this pass targets (few rooms × handful of
/// textures); a binary search lands when manifests grow.
pub fn find_asset(
    assets: &'static [LevelAssetRecord],
    id: AssetId,
) -> Option<&'static LevelAssetRecord> {
    let mut i = 0;
    while i < assets.len() {
        if assets[i].id == id {
            return Some(&assets[i]);
        }
        i += 1;
    }
    None
}

/// Like [`find_asset`] but also asserts the asset has the
/// expected kind. Use this when you're about to feed bytes to
/// a kind-specific loader (`World::from_bytes`, etc.) -- picks
/// up manifest typos that would otherwise crash inside the
/// loader.
pub fn find_asset_of_kind(
    assets: &'static [LevelAssetRecord],
    id: AssetId,
    kind: AssetKind,
) -> Option<&'static LevelAssetRecord> {
    let asset = find_asset(assets, id)?;
    if asset.kind == kind {
        Some(asset)
    } else {
        None
    }
}

/// Snapshot of one `ensure_room_resident` call. Lets the caller
/// log how many assets actually moved (vs. were already
/// resident) without re-scanning the residency lists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ResidencyChangeSet {
    /// Required RAM assets that weren't resident before this
    /// call (i.e. would have been faulted in).
    pub missing_ram_count: u16,
    /// Required VRAM assets that weren't resident before this
    /// call.
    pub missing_vram_count: u16,
    /// Required RAM assets already present.
    pub already_resident_ram_count: u16,
    /// Required VRAM assets already present.
    pub already_resident_vram_count: u16,
    /// Required RAM assets that didn't fit in the residency
    /// table (capacity exceeded).
    pub overflow_ram_count: u16,
    /// Required VRAM assets that didn't fit.
    pub overflow_vram_count: u16,
}

/// Tiny no-alloc residency tracker. Records which `AssetId`s
/// the runtime considers RAM- or VRAM-resident. Capacity is
/// fixed at compile time by `RAM_CAP` / `VRAM_CAP`; overflow
/// is reported through [`ResidencyChangeSet`] rather than
/// silently dropping assets.
///
/// This pass uses the manager only to avoid re-uploading
/// textures every frame -- eviction / LRU / stream-pack paging
/// land in later passes. RAM tracking is logical because every
/// asset is `include_bytes!`-resident from process start.
#[derive(Debug, Clone, Copy)]
pub struct ResidencyManager<const RAM_CAP: usize, const VRAM_CAP: usize> {
    ram: [Option<AssetId>; RAM_CAP],
    vram: [Option<AssetId>; VRAM_CAP],
}

impl<const RAM_CAP: usize, const VRAM_CAP: usize> Default for ResidencyManager<RAM_CAP, VRAM_CAP> {
    fn default() -> Self {
        Self::new()
    }
}

impl<const RAM_CAP: usize, const VRAM_CAP: usize> ResidencyManager<RAM_CAP, VRAM_CAP> {
    /// Empty manager. `const fn` so callers can build one in a
    /// `static` initializer if they want.
    pub const fn new() -> Self {
        Self {
            ram: [None; RAM_CAP],
            vram: [None; VRAM_CAP],
        }
    }

    /// `true` if `id` is RAM-resident.
    pub fn contains_ram(&self, id: AssetId) -> bool {
        contains(&self.ram, id)
    }

    /// `true` if `id` is VRAM-resident.
    pub fn contains_vram(&self, id: AssetId) -> bool {
        contains(&self.vram, id)
    }

    /// Mark `id` RAM-resident. Returns `true` on first insert,
    /// `false` if already present or the table is full.
    pub fn mark_ram_resident(&mut self, id: AssetId) -> bool {
        insert(&mut self.ram, id)
    }

    /// Mark `id` VRAM-resident. Returns `true` on first insert,
    /// `false` if already present or the table is full.
    pub fn mark_vram_resident(&mut self, id: AssetId) -> bool {
        insert(&mut self.vram, id)
    }

    /// Number of RAM slots in use.
    pub fn ram_len(&self) -> usize {
        self.ram.iter().filter(|s| s.is_some()).count()
    }

    /// Number of VRAM slots in use.
    pub fn vram_len(&self) -> usize {
        self.vram.iter().filter(|s| s.is_some()).count()
    }

    /// Run the residency contract for `room`: every required
    /// asset is marked resident; the returned change-set says
    /// which were already there, which were just brought in,
    /// and which couldn't fit. Caller is responsible for the
    /// actual upload (asset bytes → VRAM rect) for *missing*
    /// VRAM assets.
    pub fn ensure_room_resident(&mut self, room: &RoomResidencyRecord) -> ResidencyChangeSet {
        let mut cs = ResidencyChangeSet::default();
        for &id in room.required_ram {
            if self.contains_ram(id) {
                cs.already_resident_ram_count = cs.already_resident_ram_count.saturating_add(1);
            } else if self.mark_ram_resident(id) {
                cs.missing_ram_count = cs.missing_ram_count.saturating_add(1);
            } else {
                cs.overflow_ram_count = cs.overflow_ram_count.saturating_add(1);
            }
        }
        for &id in room.required_vram {
            if self.contains_vram(id) {
                cs.already_resident_vram_count = cs.already_resident_vram_count.saturating_add(1);
            } else if self.mark_vram_resident(id) {
                cs.missing_vram_count = cs.missing_vram_count.saturating_add(1);
            } else {
                cs.overflow_vram_count = cs.overflow_vram_count.saturating_add(1);
            }
        }
        cs
    }
}

fn contains<const N: usize>(slots: &[Option<AssetId>; N], id: AssetId) -> bool {
    let mut i = 0;
    while i < N {
        if let Some(existing) = slots[i] {
            if existing == id {
                return true;
            }
        }
        i += 1;
    }
    false
}

fn insert<const N: usize>(slots: &mut [Option<AssetId>; N], id: AssetId) -> bool {
    // First scan checks for duplicates so we don't claim two
    // slots for the same id; second scan finds the first free
    // slot. Callers that want "is resident" without inserting
    // call `contains` directly.
    let mut i = 0;
    while i < N {
        if let Some(existing) = slots[i] {
            if existing == id {
                return false;
            }
        }
        i += 1;
    }
    let mut i = 0;
    while i < N {
        if slots[i].is_none() {
            slots[i] = Some(id);
            return true;
        }
        i += 1;
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;

    static ROOM_BYTES: &[u8] = b"PSXW-stub";
    static TEX_BYTES: &[u8] = b"PSXT-stub";

    static ASSETS: &[LevelAssetRecord] = &[
        LevelAssetRecord {
            id: AssetId(0),
            kind: AssetKind::RoomWorld,
            bytes: ROOM_BYTES,
            ram_bytes: 9,
            vram_bytes: 0,
            flags: 0,
        },
        LevelAssetRecord {
            id: AssetId(1),
            kind: AssetKind::Texture,
            bytes: TEX_BYTES,
            ram_bytes: 9,
            vram_bytes: 16,
            flags: 0,
        },
    ];

    #[test]
    fn find_asset_returns_record_by_id() {
        assert_eq!(
            find_asset(ASSETS, AssetId(0)).map(|a| a.id),
            Some(AssetId(0))
        );
        assert_eq!(
            find_asset(ASSETS, AssetId(1)).map(|a| a.id),
            Some(AssetId(1))
        );
        assert!(find_asset(ASSETS, AssetId(42)).is_none());
    }

    #[test]
    fn find_asset_of_kind_filters_by_kind() {
        assert!(find_asset_of_kind(ASSETS, AssetId(0), AssetKind::RoomWorld).is_some());
        assert!(find_asset_of_kind(ASSETS, AssetId(0), AssetKind::Texture).is_none());
        assert!(find_asset_of_kind(ASSETS, AssetId(1), AssetKind::Texture).is_some());
    }

    #[test]
    fn residency_marks_missing_then_resident() {
        let mut r = ResidencyManager::<4, 4>::new();
        let room = RoomResidencyRecord {
            room: RoomIndex::ZERO,
            required_ram: &[AssetId(0)],
            required_vram: &[AssetId(1), AssetId(2)],
            warm_ram: &[],
            warm_vram: &[],
        };

        let first = r.ensure_room_resident(&room);
        assert_eq!(first.missing_ram_count, 1);
        assert_eq!(first.missing_vram_count, 2);
        assert_eq!(first.already_resident_ram_count, 0);
        assert_eq!(first.already_resident_vram_count, 0);

        let second = r.ensure_room_resident(&room);
        assert_eq!(second.missing_ram_count, 0);
        assert_eq!(second.missing_vram_count, 0);
        assert_eq!(second.already_resident_ram_count, 1);
        assert_eq!(second.already_resident_vram_count, 2);
    }

    #[test]
    fn duplicate_mark_returns_false() {
        let mut r = ResidencyManager::<4, 4>::new();
        assert!(r.mark_ram_resident(AssetId(7)));
        assert!(!r.mark_ram_resident(AssetId(7)));
        assert_eq!(r.ram_len(), 1);
    }

    #[test]
    fn residency_overflow_is_reported_not_silent() {
        let mut r = ResidencyManager::<2, 2>::new();
        let room = RoomResidencyRecord {
            room: RoomIndex::ZERO,
            required_ram: &[AssetId(1), AssetId(2), AssetId(3)],
            required_vram: &[],
            warm_ram: &[],
            warm_vram: &[],
        };
        let cs = r.ensure_room_resident(&room);
        assert_eq!(cs.missing_ram_count, 2);
        assert_eq!(cs.overflow_ram_count, 1);
        assert_eq!(r.ram_len(), 2);
    }

    #[test]
    fn streamed_room_chunk_schema_sizes_are_stable() {
        assert_eq!(STREAMED_ROOM_CHUNK_MAGIC, *b"PSXCHNK\0");
        assert_eq!(STREAMED_ROOM_CHUNK_VERSION, 3);
        assert_eq!(STREAMED_ROOM_CHUNK_HEADER_BYTES, 64);
        assert_eq!(streamed_room_chunk_header::COLLISION_OFFSET, 20);
        assert_eq!(streamed_room_chunk_header::CELL_VERTICES_OFFSET, 52);
        assert_eq!(streamed_room_chunk_header::CELL_VERTEX_COUNT, 56);
        assert_eq!(streamed_room_chunk_header::FLAGS, 60);
        assert_eq!(STREAMED_ROOM_CHUNK_FLAG_COLLISION_COMPACT, 1);
        assert_eq!(COMPACT_COLLISION_MAGIC, *b"PSXCOLL\0");
        assert_eq!(COMPACT_COLLISION_VERSION, 2);
        assert_eq!(COMPACT_COLLISION_HEADER_BYTES, 36);
        assert_eq!(COMPACT_COLLISION_SECTOR_BYTES, 48);
        assert_eq!(COMPACT_COLLISION_NO_ROOM, u16::MAX);
        assert_eq!(COMPACT_COLLISION_WALL_BYTES, 20);
        assert_eq!(COMPACT_COLLISION_HEIGHT_OVERRIDE_BYTES, 28);
        assert_eq!(core::mem::size_of::<LevelCachedRoomCellRecord>(), 36);
        assert_eq!(core::mem::size_of::<LevelCachedRoomVertexRecord>(), 12);
        assert_eq!(core::mem::size_of::<LevelCachedRoomSurfaceRecord>(), 40);
        assert_eq!(core::mem::align_of::<LevelCachedRoomCellRecord>(), 4);
        assert_eq!(core::mem::align_of::<LevelCachedRoomVertexRecord>(), 4);
        assert_eq!(core::mem::align_of::<LevelCachedRoomSurfaceRecord>(), 2);
    }
}
