//! Embedded Play cooker for authored brush worlds.

use std::fmt;
use std::path::Path;

use crate::brush_world::{
    compile_brush_world, BrushWorldCookError, BrushWorldCookMode, BrushWorldCookOptions,
    CompiledBrushTexture, CompiledBrushWorld,
};
use crate::{NodeKind, ProjectDocument};

pub const BRUSH_MANIFEST_FILENAME: &str = "brush_manifest.cooked.rs";
pub const BRUSH_WORLD_FILENAME: &str = "brush_world.pxbsp";
pub const BRUSH_TEXTURE_DIRNAME: &str = "brush_textures";
const GRID_MANIFEST_FILENAME: &str = "level_manifest.cooked.rs";
const DRAFT_AMBIENT: [u8; 3] = [32; 3];

#[derive(Debug)]
pub enum BrushPlaytestCookError {
    PlayerSpawnCount(usize),
    Compile(BrushWorldCookError),
    Io(std::io::Error),
}

impl fmt::Display for BrushPlaytestCookError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::PlayerSpawnCount(0) => {
                formatter.write_str("brush Play needs one Player Spawn; none was found")
            }
            Self::PlayerSpawnCount(count) => write!(
                formatter,
                "brush Play needs exactly one Player Spawn; found {count}"
            ),
            Self::Compile(error) => write!(formatter, "brush world compile failed: {error:?}"),
            Self::Io(error) => write!(formatter, "brush Play output failed: {error}"),
        }
    }
}

impl From<BrushWorldCookError> for BrushPlaytestCookError {
    fn from(value: BrushWorldCookError) -> Self {
        Self::Compile(value)
    }
}

impl From<std::io::Error> for BrushPlaytestCookError {
    fn from(value: std::io::Error) -> Self {
        Self::Io(value)
    }
}

/// Compile and atomically select a draft PXBSP world for embedded Play.
pub fn cook_brush_playtest_to_dir(
    project: &ProjectDocument,
    project_root: &Path,
    generated_dir: &Path,
) -> Result<CompiledBrushWorld, BrushPlaytestCookError> {
    std::fs::create_dir_all(generated_dir)?;
    clear_selected_manifests(generated_dir)?;

    let spawn_count = project
        .active_scene()
        .nodes()
        .iter()
        .filter(|node| matches!(node.kind, NodeKind::SpawnPoint { player: true, .. }))
        .count();
    if spawn_count != 1 {
        return Err(BrushPlaytestCookError::PlayerSpawnCount(spawn_count));
    }

    let compiled = compile_brush_world(
        project,
        BrushWorldCookOptions {
            project_root,
            mode: BrushWorldCookMode::Draft,
            ambient: DRAFT_AMBIENT,
            texture_asset_base: 0,
        },
    )?;
    write_brush_playtest(&compiled, generated_dir)?;
    Ok(compiled)
}

/// Write one already-compiled brush Play package, selecting it only after all
/// binary assets have landed successfully.
pub fn write_brush_playtest(
    compiled: &CompiledBrushWorld,
    generated_dir: &Path,
) -> std::io::Result<()> {
    std::fs::create_dir_all(generated_dir)?;
    clear_selected_manifests(generated_dir)?;

    let texture_dir = generated_dir.join(BRUSH_TEXTURE_DIRNAME);
    if texture_dir.exists() {
        std::fs::remove_dir_all(&texture_dir)?;
    }
    std::fs::create_dir_all(&texture_dir)?;
    std::fs::write(
        generated_dir.join(BRUSH_WORLD_FILENAME),
        &compiled.pxbsp.bytes,
    )?;
    for (index, texture) in compiled.textures.iter().enumerate() {
        std::fs::write(texture_dir.join(texture_filename(index)), &texture.bytes)?;
    }

    let source = render_brush_manifest_source(&compiled.textures);
    std::fs::write(generated_dir.join(BRUSH_MANIFEST_FILENAME), source)
}

fn clear_selected_manifests(generated_dir: &Path) -> std::io::Result<()> {
    for filename in [BRUSH_MANIFEST_FILENAME, GRID_MANIFEST_FILENAME] {
        let path = generated_dir.join(filename);
        match std::fs::remove_file(path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
    }
    Ok(())
}

fn texture_filename(index: usize) -> String {
    format!("texture_{index:03}.psxt")
}

fn render_brush_manifest_source(textures: &[CompiledBrushTexture]) -> String {
    let asset_ids = textures
        .iter()
        .map(|texture| texture.asset_id.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    let blobs = textures
        .iter()
        .enumerate()
        .map(|(index, _)| {
            format!(
                "    include_bytes!(\"{BRUSH_TEXTURE_DIRNAME}/{}\"),",
                texture_filename(index)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// Generated by the brush Play cooker.\n\
         pub static BRUSH_WORLD_PXBSP: &[u8] = include_bytes!(\"{BRUSH_WORLD_FILENAME}\");\n\
         pub static BRUSH_TEXTURE_ASSET_IDS: &[u16] = &[{asset_ids}];\n\
         pub static BRUSH_TEXTURES: &[&[u8]] = &[\n{blobs}\n];\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use psx_bsp::collision::Q12_ONE;
    use psx_bsp::mover::BrushDoorSet;
    use psx_bsp::pxbsp::{entity_class, entity_flags};
    use psx_bsp::pxbsp_resident::PxbspResidentMap;
    use psx_bsp::{SliceReader, Vec3I32};

    #[test]
    fn manifest_keeps_texture_asset_ids_aligned_with_blobs() {
        let textures = vec![
            CompiledBrushTexture {
                asset_id: 7,
                key: "stone".into(),
                bytes: vec![1],
                size: [16, 16],
            },
            CompiledBrushTexture {
                asset_id: 11,
                key: "trim".into(),
                bytes: vec![2],
                size: [32, 8],
            },
        ];
        let source = render_brush_manifest_source(&textures);
        assert!(source.contains("BRUSH_TEXTURE_ASSET_IDS: &[u16] = &[7, 11]"));
        assert!(source.contains("brush_textures/texture_000.psxt"));
        assert!(source.contains("brush_textures/texture_001.psxt"));
    }

    #[test]
    fn first_playable_fixture_opens_a_player_hull_route_through_its_door() {
        let project = ProjectDocument::from_ron_str(include_str!(
            "../../../projects/brush-first-playable/project.ron"
        ))
        .expect("brush first-playable fixture");
        let fixture_dir =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../projects/brush-first-playable");
        let compiled = compile_brush_world(
            &project,
            BrushWorldCookOptions {
                project_root: &fixture_dir,
                mode: BrushWorldCookMode::Draft,
                ambient: DRAFT_AMBIENT,
                texture_asset_base: 0,
            },
        )
        .expect("compile brush first-playable fixture");
        let mut map = PxbspResidentMap::with_capacity(compiled.pxbsp.bytes.len());
        map.load(0, &mut SliceReader::new(&compiled.pxbsp.bytes))
            .expect("load brush first-playable fixture");

        let entities = map.entities();
        let spawn = (0..entities.len())
            .filter_map(|index| entities.get(index))
            .find(|entity| {
                entity.class_id == entity_class::PLAYER_SPAWN
                    && entity.flags & entity_flags::ENABLED != 0
            })
            .expect("enabled player spawn");
        let destination = Vec3I32 {
            x: 768 * 4096,
            ..spawn.origin
        };
        let world_trace = map
            .model_collision_hull(0, 1)
            .expect("world player hull")
            .trace(spawn.origin, destination)
            .expect("world trace");
        assert_eq!(world_trace.fraction, Q12_ONE, "static doorway is clear");

        let mut doors = BrushDoorSet::<1>::default();
        doors.init_from_map(&map).expect("one runtime door");
        assert_eq!(doors.len(), 1);
        let closed_trace = map
            .model_collision_hull(1, 1)
            .expect("door player hull")
            .transformed(doors.get(0).expect("door").transform())
            .trace(spawn.origin, destination)
            .expect("closed door trace");
        assert!(
            closed_trace.fraction < Q12_ONE,
            "closed door blocks the route"
        );

        doors.get_mut(0).expect("door").set_open(true);
        for _ in 0..60 {
            doors.tick();
        }
        let open_trace = map
            .model_collision_hull(1, 1)
            .expect("door player hull")
            .transformed(doors.get(0).expect("door").transform())
            .trace(spawn.origin, destination)
            .expect("open door trace");
        assert_eq!(open_trace.fraction, Q12_ONE, "open door clears the route");

        let mut tape_doors = BrushDoorSet::<1>::default();
        tape_doors.init_from_map(&map).expect("one tape door");
        let mut tape_origin = spawn.origin;
        for tick in 0..150 {
            if tick == 24 {
                tape_doors.get_mut(0).expect("tape door").toggle();
            }
            tape_doors.tick();
            let candidate = Vec3I32 {
                x: tape_origin.x + 4 * 4096,
                ..tape_origin
            };
            let mut trace = map
                .model_collision_hull(0, 1)
                .expect("world player hull")
                .trace(tape_origin, candidate)
                .expect("tape world trace");
            let door_trace = map
                .model_collision_hull(1, 1)
                .expect("door player hull")
                .transformed(tape_doors.get(0).expect("tape door").transform())
                .trace(tape_origin, candidate)
                .expect("tape door trace");
            if door_trace.fraction < trace.fraction {
                trace = door_trace;
            }
            tape_origin = trace.end;
        }
        assert!(
            tape_origin.x >= 768 * 4096,
            "walkthrough tape reaches the second room: x={}",
            tape_origin.x >> 12
        );
    }
}
