//! Embedded Play cooker for authored brush worlds.

use std::fmt;
use std::path::Path;

use crate::brush_world::{
    compile_brush_world, BrushWorldCookError, BrushWorldCookMode, BrushWorldCookOptions,
    CompiledBrushTexture, CompiledBrushWorld,
};
use crate::{NodeKind, ProjectDocument};

pub const BRUSH_MANIFEST_FILENAME: &str = "brush_manifest.cooked.rs";
pub const BRUSH_WORLD_FILENAME: &str = "brush_world.pxbsp";
pub const BRUSH_TEXTURE_DIRNAME: &str = "brush_textures";
const GRID_MANIFEST_FILENAME: &str = "level_manifest.cooked.rs";
const DRAFT_AMBIENT: [u8; 3] = [32; 3];

#[derive(Debug)]
pub enum BrushPlaytestCookError {
    PlayerSpawnCount(usize),
    Compile(BrushWorldCookError),
    Io(std::io::Error),
}

impl fmt::Display for BrushPlaytestCookError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::PlayerSpawnCount(0) => {
                formatter.write_str("brush Play needs one Player Spawn; none was found")
            }
            Self::PlayerSpawnCount(count) => write!(
                formatter,
                "brush Play needs exactly one Player Spawn; found {count}"
            ),
            Self::Compile(error) => write!(formatter, "brush world compile failed: {error:?}"),
            Self::Io(error) => write!(formatter, "brush Play output failed: {error}"),
        }
    }
}

impl From<BrushWorldCookError> for BrushPlaytestCookError {
    fn from(value: BrushWorldCookError) -> Self {
        Self::Compile(value)
    }
}

impl From<std::io::Error> for BrushPlaytestCookError {
    fn from(value: std::io::Error) -> Self {
        Self::Io(value)
    }
}

/// Compile and atomically select a draft PXBSP world for embedded Play.
pub fn cook_brush_playtest_to_dir(
    project: &ProjectDocument,
    project_root: &Path,
    generated_dir: &Path,
) -> Result<CompiledBrushWorld, BrushPlaytestCookError> {
    std::fs::create_dir_all(generated_dir)?;
    clear_selected_manifests(generated_dir)?;

    let spawn_count = project
        .active_scene()
        .nodes()
        .iter()
        .filter(|node| matches!(node.kind, NodeKind::SpawnPoint { player: true, .. }))
        .count();
    if spawn_count != 1 {
        return Err(BrushPlaytestCookError::PlayerSpawnCount(spawn_count));
    }

    let compiled = compile_brush_world(
        project,
        BrushWorldCookOptions {
            project_root,
            mode: BrushWorldCookMode::Draft,
            ambient: DRAFT_AMBIENT,
            texture_asset_base: 0,
        },
    )?;
    write_brush_playtest(&compiled, generated_dir)?;
    Ok(compiled)
}

/// Write one already-compiled brush Play package, selecting it only after all
/// binary assets have landed successfully.
pub fn write_brush_playtest(
    compiled: &CompiledBrushWorld,
    generated_dir: &Path,
) -> std::io::Result<()> {
    std::fs::create_dir_all(generated_dir)?;
    clear_selected_manifests(generated_dir)?;

    let texture_dir = generated_dir.join(BRUSH_TEXTURE_DIRNAME);
    if texture_dir.exists() {
        std::fs::remove_dir_all(&texture_dir)?;
    }
    std::fs::create_dir_all(&texture_dir)?;
    std::fs::write(
        generated_dir.join(BRUSH_WORLD_FILENAME),
        &compiled.pxbsp.bytes,
    )?;
    for (index, texture) in compiled.textures.iter().enumerate() {
        std::fs::write(texture_dir.join(texture_filename(index)), &texture.bytes)?;
    }

    let source = render_brush_manifest_source(&compiled.textures);
    std::fs::write(generated_dir.join(BRUSH_MANIFEST_FILENAME), source)
}

fn clear_selected_manifests(generated_dir: &Path) -> std::io::Result<()> {
    for filename in [BRUSH_MANIFEST_FILENAME, GRID_MANIFEST_FILENAME] {
        let path = generated_dir.join(filename);
        match std::fs::remove_file(path) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
    }
    Ok(())
}

fn texture_filename(index: usize) -> String {
    format!("texture_{index:03}.psxt")
}

fn render_brush_manifest_source(textures: &[CompiledBrushTexture]) -> String {
    let asset_ids = textures
        .iter()
        .map(|texture| texture.asset_id.to_string())
        .collect::<Vec<_>>()
        .join(", ");
    let blobs = textures
        .iter()
        .enumerate()
        .map(|(index, _)| {
            format!(
                "    include_bytes!(\"{BRUSH_TEXTURE_DIRNAME}/{}\"),",
                texture_filename(index)
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "// Generated by the brush Play cooker.\n\
         pub static BRUSH_WORLD_PXBSP: &[u8] = include_bytes!(\"{BRUSH_WORLD_FILENAME}\");\n\
         pub static BRUSH_TEXTURE_ASSET_IDS: &[u16] = &[{asset_ids}];\n\
         pub static BRUSH_TEXTURES: &[&[u8]] = &[\n{blobs}\n];\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn manifest_keeps_texture_asset_ids_aligned_with_blobs() {
        let textures = vec![
            CompiledBrushTexture {
                asset_id: 7,
                key: "stone".into(),
                bytes: vec![1],
                size: [16, 16],
            },
            CompiledBrushTexture {
                asset_id: 11,
                key: "trim".into(),
                bytes: vec![2],
                size: [32, 8],
            },
        ];
        let source = render_brush_manifest_source(&textures);
        assert!(source.contains("BRUSH_TEXTURE_ASSET_IDS: &[u16] = &[7, 11]"));
        assert!(source.contains("brush_textures/texture_000.psxt"));
        assert!(source.contains("brush_textures/texture_001.psxt"));
    }
}
