//! Stateless rendering and collision policy for cooked CylinderProps.
//!
//! Geometry is generated by the host-side editor/cooker. Runtime work is
//! limited to room/cull checks, projection, fog, and packet submission.

use crate::image_props::average_vertex_rgb;
use crate::model_rendering::{model_override_blend_mode, sphere_visible_to_camera};
use crate::room_lighting::RuntimeRoomLighting;
use crate::vram::VramSlot;
use psx_engine::{
    CharacterCollisionCylinder, CullMode, DepthPolicy, LoadedWorldCameraGte, PrimitiveSink,
    RoomPoint, WorldCamera, WorldRenderPass, WorldSurfaceOptions, WorldVertex,
};
use psx_gpu::{
    material::TextureMaterial,
    prim::{QuadTexturedGouraud, TriTextured, TriTexturedGouraud},
};
use psx_level::{
    cylinder_prop_flags, AssetId, LevelCylinderPropRecord, LevelCylinderPropSurfaceRecord,
    RoomIndex,
};

#[derive(Clone, Copy)]
struct CylinderTextureRuntime {
    asset: AssetId,
    material: TextureMaterial,
}

/// Draw all cooked CylinderProps in `current_room`.
pub fn draw_cylinder_props<T, const OT_DEPTH: usize, const USE_STATIC_PROP_QUAD_LEAF: bool>(
    props: &[LevelCylinderPropRecord],
    surfaces: &[LevelCylinderPropSurfaceRecord],
    current_room: RoomIndex,
    camera: &WorldCamera,
    options: WorldSurfaceOptions,
    lighting: &RuntimeRoomLighting,
    mut prop_texture_slot: impl FnMut(AssetId) -> Option<VramSlot>,
    triangles: &mut T,
    world: &mut WorldRenderPass<'_, '_, OT_DEPTH>,
) where
    T: PrimitiveSink<TriTextured>
        + PrimitiveSink<TriTexturedGouraud>
        + PrimitiveSink<QuadTexturedGouraud>,
{
    let mut projector = None;
    let mut texture_cache: Option<CylinderTextureRuntime> = None;
    for prop in props {
        if prop.room != current_room
            || !sphere_visible_to_camera(
                camera,
                options,
                WorldVertex::new(prop.center[0], prop.center[1], prop.center[2]),
                prop.cull_radius,
                96,
            )
        {
            continue;
        }
        let loaded = match projector {
            Some(projector) => projector,
            None => {
                let loaded = LoadedWorldCameraGte::load(*camera);
                projector = Some(loaded);
                loaded
            }
        };
        let first = usize::from(prop.surface_first);
        let end = first
            .saturating_add(usize::from(prop.surface_count))
            .min(surfaces.len());
        for surface in surfaces.get(first..end).unwrap_or(&[]) {
            let slot = usize::from(surface.material_slot);
            if slot >= psx_level::CYLINDER_PROP_MATERIAL_COUNT
                || !surface_front_facing(camera, surface)
            {
                continue;
            }
            let Some(texture_asset) = prop.texture_assets[slot] else {
                continue;
            };
            let texture = match texture_cache {
                Some(cached) if cached.asset == texture_asset => cached,
                _ => {
                    let Some(vram) = prop_texture_slot(texture_asset) else {
                        continue;
                    };
                    let runtime = CylinderTextureRuntime {
                        asset: texture_asset,
                        material: TextureMaterial::opaque(
                            vram.clut_word,
                            vram.tpage_word,
                            (0x80, 0x80, 0x80),
                        )
                        .with_blend_mode(model_override_blend_mode(prop.blend_modes[slot]))
                        .with_texture_window(vram.texture_window),
                    };
                    texture_cache = Some(runtime);
                    runtime
                }
            };
            let vertices = surface
                .vertices
                .map(|vertex| WorldVertex::new(vertex[0], vertex[1], vertex[2]));
            let Some(projected) = loaded.project_world_quad(vertices) else {
                let colors = surface.baked_vertex_rgb;
                let material = texture.material.with_tint(average_vertex_rgb(colors));
                let opts = options
                    .with_depth_policy(DepthPolicy::Average)
                    .with_cull_mode(CullMode::None)
                    .with_material_layer(material)
                    .with_textured_triangle_splitting(true)
                    .with_textured_triangle_max_edge(0);
                let uvs = surface.uv_q8.map(|uv| (uv[0], uv[1]));
                if surface.vertex_count == 3 {
                    let _ = world.submit_textured_world_triangle(
                        triangles,
                        *camera,
                        [vertices[0], vertices[1], vertices[2]],
                        [uvs[0], uvs[1], uvs[2]],
                        material,
                        opts,
                    );
                } else {
                    let _ = world.submit_textured_world_quad(
                        triangles, *camera, vertices, uvs, material, opts,
                    );
                }
                continue;
            };
            let colors = [
                lighting.apply_fog_at_depth(surface.baked_vertex_rgb[0], projected[0].sz),
                lighting.apply_fog_at_depth(surface.baked_vertex_rgb[1], projected[1].sz),
                lighting.apply_fog_at_depth(surface.baked_vertex_rgb[2], projected[2].sz),
                lighting.apply_fog_at_depth(surface.baked_vertex_rgb[3], projected[3].sz),
            ];
            let uvs = surface.uv_q8.map(|uv| (uv[0], uv[1]));
            if surface.vertex_count == 3 {
                let opts = options
                    .with_depth_policy(DepthPolicy::Average)
                    .with_cull_mode(CullMode::None)
                    .with_material_layer(texture.material)
                    .with_textured_triangle_splitting(true)
                    .with_textured_triangle_max_edge(0);
                let _ = world.submit_textured_gouraud_triangle_prescreened_u8(
                    triangles,
                    [projected[0], projected[1], projected[2]],
                    [uvs[0], uvs[1], uvs[2]],
                    [colors[0], colors[1], colors[2]],
                    texture.material,
                    opts,
                );
            } else if USE_STATIC_PROP_QUAD_LEAF {
                let _ = world.submit_static_prop_textured_gouraud_quad_prescreened_u8(
                    triangles,
                    &projected,
                    &uvs,
                    &colors,
                    texture.material,
                    &options,
                );
            } else {
                let opts = options
                    .with_depth_policy(DepthPolicy::Average)
                    .with_cull_mode(CullMode::None)
                    .with_material_layer(texture.material)
                    .with_textured_triangle_splitting(true)
                    .with_textured_triangle_max_edge(0);
                let _ = world.submit_textured_gouraud_quad_prescreened_u8(
                    triangles,
                    &projected,
                    &uvs,
                    &colors,
                    texture.material,
                    opts,
                );
            }
        }
    }
}

/// Append one conservative radial blocker per collidable CylinderProp.
///
/// Collision stays O(props) and never touches generated render surfaces. An
/// elliptical or tilted prop uses the larger cooked horizontal extent, keeping
/// the blocker conservative while avoiding the false corners of an AABB.
pub fn collect_cylinder_prop_collision_blockers(
    props: &[LevelCylinderPropRecord],
    room: RoomIndex,
    out: &mut [CharacterCollisionCylinder],
) -> usize {
    let mut count = 0usize;
    for prop in props {
        if prop.room != room
            || prop.flags & cylinder_prop_flags::COLLISION_ENABLED == 0
            || count >= out.len()
        {
            continue;
        }
        let span_x = prop.bounds_max[0].saturating_sub(prop.bounds_min[0]);
        let span_y = prop.bounds_max[1].saturating_sub(prop.bounds_min[1]);
        let span_z = prop.bounds_max[2].saturating_sub(prop.bounds_min[2]);
        let radius = span_x.max(span_z).saturating_add(1) / 2;
        if radius <= 0 || span_y <= 0 {
            continue;
        }
        out[count] = CharacterCollisionCylinder::new(
            RoomPoint::new(
                prop.bounds_min[0].saturating_add(span_x / 2),
                prop.bounds_min[1],
                prop.bounds_min[2].saturating_add(span_z / 2),
            ),
            radius,
            span_y,
        );
        count += 1;
    }
    count
}

fn surface_front_facing(camera: &WorldCamera, surface: &LevelCylinderPropSurfaceRecord) -> bool {
    let vx = camera.position.x.saturating_sub(surface.center[0]);
    let vy = camera.position.y.saturating_sub(surface.center[1]);
    let vz = camera.position.z.saturating_sub(surface.center[2]);
    surface.normal[0]
        .saturating_mul(vx)
        .saturating_add(surface.normal[1].saturating_mul(vy))
        .saturating_add(surface.normal[2].saturating_mul(vz))
        > 0
}
