"""Build opaque 128x128 / 16-colour material trials. No mesh changes.

--install selects one trial for the cannon, scarf and stance fragments.
HRZ receives an amber scarf/fragment palette only; its weapon remains melee.
"""
from pathlib import Path
from PIL import Image
import argparse, math, struct, json, subprocess, sys

SOURCE = Path(__file__).resolve().parent
PROJECT = SOURCE.parents[3]
ROOT = PROJECT.parents[2]
OUT = PROJECT/'validation/material-review-v3'
PROFILES = {
    'pearl': {'label':'A - Pearl crystal', 'floor':10, 'ceiling':31, 'white':13},
    'jade': {'label':'B - Polished jade', 'floor':4, 'ceiling':31, 'white':23},
    'satin': {'label':'C - Satin mineral', 'floor':10, 'ceiling':28, 'white':30},
}

def palette(profile, colour):
    p=PROFILES[profile]; result=[]
    for i in range(16):
        level=p['floor']+(p['ceiling']-p['floor'])*i/15
        white=max(0,min(1,(level-p['white'])/(31-p['white'])))
        result.append(tuple(round((c/255*level+(level-c/255*level)*white)*255/31) for c in colour))
    return result

def image_for(profile, colours):
    im=Image.new('P',(128,128)); im.putpalette([c for rgb in colours for c in rgb]+[0]*(768-48))
    pixels=[]
    for y in range(128):
        for x in range(128):
            if profile=='satin':
                value=.18+.58*(1-y/127)+.16*math.exp(-((x-46)/55)**2)
            else:
                value=.08+.65*math.exp(-((x-32)/58)**2-((y-27)/62)**2)
                value+=.34*math.exp(-((x+.40*y-108)/21)**2)
            pixels.append(round(max(0,min(1,value))*15))
    im.putdata(pixels); return im

def psxt(im):
    px=im.tobytes(); packed=bytes(px[i]|px[i+1]<<4 for i in range(0,len(px),2))
    pal=im.getpalette(); words=[]
    for i in range(16):
        r,g,b=pal[i*3:i*3+3]; words.append((r>>3)|(g>>3)<<5|(b>>3)<<10)
    clut=struct.pack('<16H',*words)
    return b'PSXT'+struct.pack('<HHIBBHHHII',1,0,16+len(packed)+len(clut),4,0,128,128,16,len(packed),len(clut))+packed+clut

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--install',choices=PROFILES);args=ap.parse_args();OUT.mkdir(parents=True,exist_ok=True)
    for name in PROFILES:
        for stance,colour in [('zth',(108,224,198)),('hrz',(255,113,58))]:
            im=image_for(name,palette(name,colour));im.save(OUT/f'{name}-{stance}-128.png',bits=4)
            (OUT/f'{name}-{stance}.psxt').write_bytes(psxt(im))
    if args.install:
        name=args.install
        (PROJECT/'assets/models/zenith_projector/iris-crystal.psxt').write_bytes((OUT/f'{name}-zth.psxt').read_bytes())
        for stance,dest in [('zth','iris-gradient-128-4bit.png'),('hrz','scarf-hrz-gradient-128-4bit.png')]:
            (SOURCE/dest).write_bytes((OUT/f'{name}-{stance}-128.png').read_bytes())
        for stance,col,file in [('zth',(108,224,198),'palette.json'),('hrz',(255,113,58),'palette-hrz.json')]:
            (SOURCE/file).write_text(json.dumps({'variant':name, 'size':[128,128],
                'bits_per_pixel':4, 'opaque':True, 'palette_rgb':palette(name,col),
                'usage':['ZTH cannon','ZTH scarf'] if stance=='zth' else ['HRZ scarf','stance-change fragments']},indent=2)+'\n')
        code=['// Generated by Graybox Reach zenith_cannon_v2/material_trials.py.',
              '// Opaque BGR555 ramps shared with the 4bpp cannon atlas.',
              f'// Selected material: {PROFILES[name]["label"]}.',
              'pub(super) const STANCE_CRYSTAL_PALETTES: [[u16; 16]; 2] = [']
        for col in [(255,113,58),(108,224,198)]:
            words=[(r>>3)|(g>>3)<<5|(b>>3)<<10 for r,g,b in palette(name,col)]
            code.append('    ['+', '.join(f'0x{v:04x}' for v in words)+'],')
        code.append('];\n')
        (ROOT/'engine/examples/editor-playtest/src/crystal_palette.rs').write_text('\n'.join(code))
        (SOURCE/'material-direction.json').write_text(json.dumps({'selected':name,'opaque':True,'texture_size':[128,128],'bits_per_pixel':4,'HRZ':'melee; amber scarf and transition only','ZTH':'ranged; mint cannon and scarf','trials':PROFILES},indent=2)+'\n')
    # New banded meshes require the matching four-strip atlas after palette changes.
    if args.install and (SOURCE/'cannon-finishes.json').exists():
        subprocess.run([sys.executable,str(SOURCE/'cannon_texture.py')],check=True)
    print('Generated opaque 4bpp trials'+(f'; installed {args.install}' if args.install else ''))
if __name__=='__main__': main()
